def discussion_units_sandbox_page_html() -> str:
    return """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Discussion Units Sandbox | iLIT</title>
<style>
:root{--paper:#f3f0e7;--surface:#fffdf7;--ink:#202522;--muted:#68716b;--line:#d8d5ca;--teal:#176c68;--soft:#eaf2ef;--rust:#a4412b}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.55 Georgia,"Times New Roman",serif}main{max-width:1160px;margin:0 auto;padding:28px 20px 56px}.kicker{color:var(--rust);font:700 11px/1.2 Arial,sans-serif;letter-spacing:.12em;text-transform:uppercase}.header{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;border-bottom:1px solid var(--line);padding-bottom:18px}.header h1{margin:7px 0 0;font-size:36px;font-weight:600}.header p{max-width:520px;margin:5px 0 0;color:var(--muted);font:14px/1.5 Arial,sans-serif}.badge{padding:7px 10px;border:1px solid var(--line);background:var(--surface);color:var(--teal);font:700 11px Arial,sans-serif;white-space:nowrap}.search{margin-top:22px;padding:16px;border:1px solid var(--line);background:var(--surface)}.search form{display:flex;gap:8px}.search input{min-width:0;flex:1;padding:12px;border:1px solid #aaa99f;background:#fff;font:16px Georgia,serif}.search button{padding:0 18px;border:0;background:var(--ink);color:#fff;font:700 11px Arial,sans-serif;letter-spacing:.06em;text-transform:uppercase}.status{margin-top:10px;color:var(--muted);font:12px Arial,sans-serif}.results{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.25fr);gap:18px;margin-top:18px}.list,.reader{border:1px solid var(--line);background:var(--surface)}.list-head,.reader-head{padding:13px 16px;border-bottom:1px solid var(--line);font:700 11px Arial,sans-serif;letter-spacing:.09em;text-transform:uppercase;color:var(--muted)}.result{display:block;width:100%;padding:13px 16px;border:0;border-bottom:1px solid var(--line);background:transparent;text-align:left;cursor:pointer}.result:hover,.result.active{background:var(--soft)}.result strong{display:block;font-size:17px;font-weight:600}.meta{margin-top:4px;color:var(--muted);font:12px/1.45 Arial,sans-serif}.reader-body{padding:20px}.reader-body h2{margin:0;font-size:27px;font-weight:600}.reader-body .meta{margin:7px 0 18px}.paragraph{padding:10px 0;border-top:1px solid var(--line)}.paragraph:first-child{border-top:0}.paragraph small{display:block;margin-bottom:3px;color:var(--teal);font:700 10px Arial,sans-serif;letter-spacing:.08em;text-transform:uppercase}.empty{padding:22px;color:var(--muted);font-family:Arial,sans-serif}.error{color:var(--rust)}
 .reader-head label{float:right;font:11px Arial,sans-serif;letter-spacing:0;text-transform:none;color:var(--teal)}.paragraph{display:grid;grid-template-columns:minmax(0,1fr) minmax(180px,.55fr);gap:16px}.assessment{align-self:start;padding:10px;border-left:3px solid var(--teal);background:var(--soft);font:12px/1.45 Arial,sans-serif}.assessment strong,.assessment span{display:block}.assessment span{margin-top:3px;color:var(--muted)}.assessment p{margin:7px 0 0}@media(max-width:760px){main{padding:20px 12px 40px}.header{display:block}.badge{display:inline-block;margin-top:14px}.header h1{font-size:30px}.search form{display:grid;grid-template-columns:1fr}.search button{min-height:42px}.results{grid-template-columns:1fr}.reader{min-height:260px}.paragraph{display:block}.assessment{margin-top:12px}}
</style>
</head>
<body><main>
<header class="header"><div><div class="kicker">Experimental research surface</div><h1>Discussion Units Sandbox</h1><p>A separate search and reader for the 300-case Discussion Unit cohort. Results and reader requests are read-only and do not change the active case library.</p></div><div class="badge">300 CASES / SANDBOX</div></header>
<section class="search" aria-label="Search the experimental cohort"><form id="searchForm"><input id="query" autocomplete="off" placeholder="Search title or citation" aria-label="Search title or citation"><button type="submit">Search</button></form><div id="status" class="status">Loading the cohort...</div></section>
<section class="results"><div class="list"><div class="list-head">Cohort cases</div><div id="results" class="empty">Search to begin.</div></div><div class="reader"><div class="reader-head">Experimental reader <label><input id="assessmentToggle" type="checkbox"> Show paragraph assessments</label></div><div id="reader" class="empty">Choose a case to inspect its source-preserved paragraphs.</div></div></section>
</main>
<script>
const results=document.getElementById('results');const reader=document.getElementById('reader');const status=document.getElementById('status');
function formatDate(value){return value?new Date(value).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'Date unavailable'}
function showResults(items){results.innerHTML='';if(!items.length){results.innerHTML='<div class="empty">No cohort cases matched that search.</div>';return}items.forEach(item=>{const button=document.createElement('button');button.className='result';button.type='button';button.innerHTML='<strong>'+escapeHtml(item.title||'Untitled case')+'</strong><div class="meta">'+escapeHtml(item.citation||'Citation unavailable')+' · '+formatDate(item.date)+' · '+escapeHtml(item.court||'Court unavailable')+'</div>';button.addEventListener('click',()=>loadReader(item.case_id,button));results.appendChild(button)})}
function escapeHtml(value){return String(value).replace(/[&<>\"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[character]))}
async function search(query=''){status.textContent='Searching the 300-case cohort...';try{const response=await fetch('/discussion-units-sandbox/search?query='+encodeURIComponent(query));if(!response.ok)throw new Error('Search failed ('+response.status+')');const data=await response.json();status.textContent=data.results.length+' result(s) from '+data.cohort_size+' cohort cases';showResults(data.results)}catch(error){status.textContent=error.message;results.innerHTML='<div class="empty error">The sandbox search is unavailable.</div>'}}
async function loadReader(caseId,button){document.querySelectorAll('.result').forEach(item=>item.classList.remove('active'));button.classList.add('active');reader.innerHTML='<div class="empty">Loading source-preserved reader...</div>';try{const response=await fetch('/discussion-units-sandbox/cases/'+caseId+'/reader-data');if(!response.ok)throw new Error('Reader failed ('+response.status+')');const data=await response.json();let assessments={};if(document.getElementById('assessmentToggle').checked){const assessmentResponse=await fetch('/discussion-units-sandbox/cases/'+caseId+'/paragraph-assessments');if(assessmentResponse.ok){const assessmentData=await assessmentResponse.json();assessments=assessmentData.assessments||{};if(!assessmentData.available)status.textContent='No paragraph assessment is available for this case.'}}const paragraphs=(data.chunks||[]).map((chunk,index)=>{const number=String(chunk.paragraph_start??index+1);const assessment=assessments[number];const panel=assessment?'<aside class="assessment"><strong>'+escapeHtml(assessment.topic||'Unclassified')+'</strong><span>'+escapeHtml(assessment.role||'Role unavailable')+' · confidence '+escapeHtml(assessment.confidence??'n/a')+'</span><p>'+escapeHtml(assessment.explanation||'')+'</p></aside>':'';return '<article class="paragraph"><div><small>Paragraph '+number+'</small>'+escapeHtml(chunk.text||'')+'</div>'+panel+'</article>'}).join('');reader.innerHTML='<div class="reader-body"><h2>'+escapeHtml(data.case.title||'Untitled case')+'</h2><div class="meta">'+escapeHtml(data.case.citation||'Citation unavailable')+' · '+escapeHtml(data.case.court||'Court unavailable')+' · '+formatDate(data.case.date)+'</div>'+(paragraphs||'<div class="empty">No readable chunks are available.</div>')+'</div>'}catch(error){reader.innerHTML='<div class="empty error">'+escapeHtml(error.message)+'</div>'}}
document.getElementById('assessmentToggle').addEventListener('change',()=>{const active=document.querySelector('.result.active');if(active)active.click()});
document.getElementById('searchForm').addEventListener('submit',event=>{event.preventDefault();search(document.getElementById('query').value)});search('');
</script></body></html>"""
