/* Citation Intelligence and Judge Profile snapshot views.
   Replaces the stacked legacy renderers for these two tabs; the legacy panels stay in the DOM, hidden. */
(function(){
const E=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const N=v=>Number(v||0).toLocaleString('en-CA');
const $=id=>document.getElementById(id);
const yearOf=d=>String(d||'').slice(0,4);
const debounce=(fn,ms)=>{let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}};
const getJSON=async url=>{const r=await fetch(url);if(!r.ok)throw new Error('Request failed ('+r.status+')');return r.json()};
const openCase=id=>{if(typeof openDecision==='function')openDecision(Number(id))};
const setParams=fn=>{const u=new URL(location.href);fn(u.searchParams);history.replaceState(null,'',u)};
const bars=(rows,color)=>{const max=Math.max(...rows.map(r=>r.value),1);return rows.map(r=>`<div class="ix-bar"><span class="n" title="${E(r.label)}">${E(r.label)}</span><span class="t"><i style="width:${Math.max(2,r.value/max*100).toFixed(1)}%;${r.color||color?'background:'+(r.color||color):''}"></i></span><span class="c">${E(r.text!=null?r.text:N(r.value))}</span></div>`).join('')};
const split=(parts,cls)=>{const total=parts.reduce((s,p)=>s+p.value,0)||1;return `<div class="ix-split ${cls||''}">${parts.filter(p=>p.value>0).map(p=>`<i title="${E(p.label)}: ${N(p.value)}" style="width:${p.value/total*100}%;background:${p.color}">${cls==='rate'&&p.value/total>.12?Math.round(p.value/total*100)+'%':''}</i>`).join('')}</div><div class="ix-legend">${parts.map(p=>`<span><i style="background:${p.color}"></i>${E(p.label)} <b>${N(p.value)}</b></span>`).join('')}</div>`};
const GOV='#a4412b',IND='#176c68',UNK='#c9c5b6',MIX='#c28e2d';
const outcomePill=o=>o==='won'?'<span class="ix-pill red">Government won</span>':o==='lost'?'<span class="ix-pill green">Government lost</span>':o==='mixed'?'<span class="ix-pill amber">Mixed</span>':'<span class="ix-pill">Not coded</span>';
const junkName=s=>{const t=String(s||'').toLowerCase();return !t||t.includes('translation')||t==='unknown'||t==='n/a'||t.includes('certified')||t.length<3};

/* ---------------- Judge profiles ---------------- */
const jp={list:null,slug:null,data:null,q:'',court:'',sort:'count',f:{outcome:'',q:'',year:''},shown:20,minister:'',issueData:null,issueError:'',issueLoading:false,issueRequest:0};
const titleCase=t=>t===t.toUpperCase()?t.toLowerCase().replace(/(^|[ '-])([a-z])/g,(m,a,b)=>a+b.toUpperCase()):t;
function jpName(raw){const s=String(raw||'').trim(),low=s.toLowerCase(),i=low.lastIndexOf('justice ');if(i>=0){const rest=s.slice(i+8).trim();const pre=low.includes('associate chief justice')?'Associate Chief Justice ':low.includes('chief justice')?'Chief Justice ':'Justice ';return pre+titleCase(rest)}return titleCase(s)}
function jpShell(){const panel=$('judgeProfilePanel');if(!panel||$('jpApp'))return;panel.insertAdjacentHTML('beforeend',`<div id="jpApp"><div class="ix-head"><div><div class="ix-eyebrow">Judicial profiles</div><h2>Judge Profiles</h2><p>Pick a judge to see their decision history, how often the government and individuals succeeded, the cases they heard and what kinds of matters they decide.</p></div></div><div class="jp-layout"><aside class="jp-rail"><div class="ix-search"><input id="jpSearch" type="search" placeholder="Search judges, e.g. Zinn" autocomplete="off" aria-label="Search judges"></div><div class="ix-chips" id="jpCourts"></div><div class="ix-chips"><label for="jpSort" style="font-size:12px;color:var(--muted)">Sort</label><select id="jpSort" style="font-size:12px;padding:4px 6px;border:1px solid var(--border);border-radius:6px;background:var(--surface)"><option value="count">Most decisions</option><option value="name">Name A to Z</option></select></div><div class="jp-list" id="jpList"><div class="ix-load">Loading judges...</div></div></aside><section class="jp-main" id="jpMain"><div class="ix-empty"><b>Select a judge</b>Choose a name on the left to open a profile snapshot.</div></section></div></div>`);
$('jpSearch').addEventListener('input',debounce(e=>{jp.q=e.target.value.trim();jpRenderList()},120));
$('jpSort').addEventListener('change',e=>{jp.sort=e.target.value;jpRenderList()});
$('jpCourts').addEventListener('click',e=>{const b=e.target.closest('[data-court]');if(!b)return;jp.court=b.dataset.court;jpRenderList()});
$('jpList').addEventListener('click',e=>{const b=e.target.closest('[data-slug]');if(b)jpSelect(b.dataset.slug)});
$('jpMain').addEventListener('click',jpMainClick);
$('jpMain').addEventListener('input',e=>{if(e.target.id==='jpFq'){jp.f.q=e.target.value;jp.shown=20;jpRenderDecisions()}});
$('jpMain').addEventListener('change',e=>{if(e.target.id==='jpFy'){jp.f.year=e.target.value;jp.shown=20;jpRenderDecisions()}else if(e.target.id==='jpFs'){jp.f.sort=e.target.value;jp.shown=20;jpRenderDecisions()}else if(e.target.id==='jpMin'){jp.minister=e.target.value;jpSelect(jp.slug,true)}})}
async function jpInit(){jpShell();if(!jp.list){try{jp.list=await getJSON('/api/judge-profiles?limit=500')}catch(err){$('jpList').innerHTML=`<div class="ix-empty">${E(err.message)}</div>`;return}}
jpRenderList();const slug=new URLSearchParams(location.search).get('judge');if(slug&&slug!==jp.slug)jpSelect(slug)}
function jpRenderList(){const list=jp.list||[],q=jp.q.toLowerCase(),courts={};list.forEach(p=>{const c=p.primary_court||'Other';courts[c]=(courts[c]||0)+1});
$('jpCourts').innerHTML=`<button class="ix-chip ${jp.court?'':'on'}" data-court="">All <em>${list.length}</em></button>`+Object.keys(courts).sort((a,b)=>courts[b]-courts[a]).slice(0,4).map(c=>`<button class="ix-chip ${jp.court===c?'on':''}" data-court="${E(c)}">${E(c)} <em>${courts[c]}</em></button>`).join('');
let rows=list.filter(p=>(!jp.court||(p.primary_court||'Other')===jp.court)&&(!q||(p.display_name+' '+(p.aliases||[]).join(' ')).toLowerCase().includes(q)));
rows=rows.slice().sort((a,b)=>jp.sort==='name'?jpName(a.display_name).localeCompare(jpName(b.display_name)):(b.decision_count||0)-(a.decision_count||0));
const max=Math.max(...list.map(p=>p.decision_count||0),1);
$('jpList').innerHTML=rows.length?rows.map(p=>`<button class="jp-item ${p.slug===jp.slug?'on':''}" data-slug="${E(p.slug)}"><b>${E(jpName(p.display_name))}<span>${N(p.decision_count)}</span></b><span class="jbar"><i style="width:${(p.decision_count||0)/max*100}%"></i></span></button>`).join(''):'<div class="ix-empty"><b>No judges match</b>Try a shorter name.</div>'}
async function jpSelect(slug,keepFilters){if(!slug)return;jpShell();if(jp.slug!==slug){jp.issueData=null;jp.issueError='';jp.issueLoading=false;jp.issueRequest++}jp.slug=slug;if(!keepFilters){jp.minister='';jp.f={outcome:'',q:'',year:''};jp.shown=20}
setParams(p=>{p.set('judge',slug);p.delete('minister')});jpRenderList();$('jpMain').innerHTML='<div class="ix-load">Loading profile...</div>';
try{jp.data=await getJSON('/api/judge-profiles/'+encodeURIComponent(slug)+(jp.minister?'?minister='+encodeURIComponent(jp.minister):''))}catch(err){$('jpMain').innerHTML=`<div class="ix-empty"><b>Could not load this profile</b>${E(err.message)}</div>`;return}
jpRender();const sel=document.querySelector('.jp-item.on');if(sel&&sel.scrollIntoView)sel.scrollIntoView({block:'nearest'})}
function tally(items,key,fallback){const m={};items.forEach(i=>{const k=(i[key]||fallback||'').toString().trim();if(!k)return;m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function keyCard(dec){const has=dec.some(x=>x.cited_by_cases!=null);if(!has)return '';const top=dec.filter(x=>Number(x.cited_by_cases)>0).sort((a,b)=>(b.cited_by_cases-a.cited_by_cases)||(b.cited_by_appeal_courts-a.cited_by_appeal_courts)).slice(0,8);
return `<div class="ix-card wide" id="jpKey"><h4>Key decisions</h4><p class="ix-note">This judge's most influential decisions, ranked by how many other decisions cite them. The second figure counts citations from the Federal Court of Appeal and Supreme Court.</p><div class="ix-list">${top.map((x,i)=>`<div class="ix-row"><div><div class="tt">${i+1}. ${E(x.title||'Untitled decision')}</div><div class="mm"><span>${E(x.citation||'No citation')}</span><span>${E(x.date||'')}</span><span><b>${N(x.cited_by_cases)}</b> citing decision${x.cited_by_cases>1?'s':''}</span>${x.cited_by_appeal_courts?`<span><b>${N(x.cited_by_appeal_courts)}</b> from FCA or SCC</span>`:''}${outcomePill(x.government_outcome)}${x.case_type?`<span>${E(x.case_type)}</span>`:''}</div></div><button class="ix-btn ix-open" data-open="${x.case_id}">Open</button></div>`).join('')||'<div class="ix-empty">None of this judge\'s decisions in this view are cited by other decisions yet.</div>'}</div></div>`}
function jpRender(){const d=jp.data,p=d.profile,o=d.outcomes||{},dec=d.decisions||[],yr=d.yearly_decisions||[];
const alias=(p.aliases||[]).filter(a=>a!==p.display_name);
const classified=Number(o.classified||0),gw=Number(o.government_wins||0),iw=Number(o.individual_wins||0),un=Number(o.unclassified||0);
const years=yr.map(y=>Number(y.year)).filter(Boolean),first=years.length?Math.min(...years):'',last=years.length?Math.max(...years):'';
const busiest=yr.slice().sort((a,b)=>b.decisions-a.decisions)[0];
const byYear={};dec.forEach(x=>{const y=yearOf(x.date);if(!y)return;const r=byYear[y]||(byYear[y]={g:0,i:0,u:0});if(x.government_outcome==='won')r.g++;else if(x.government_outcome==='lost')r.i++;else r.u++});
const ys=Object.keys(byYear).map(Number).sort((a,b)=>a-b);const allY=[];if(ys.length)for(let y=ys[0];y<=ys[ys.length-1];y++)allY.push(String(y));
const maxY=Math.max(...allY.map(y=>{const r=byYear[y];return r?r.g+r.i+r.u:0}),1);
const chart=allY.length?`<div class="ix-years">${allY.map(y=>{const r=byYear[y]||{g:0,i:0,u:0},t=r.g+r.i+r.u,h=t/maxY*100;return `<div class="yc" title="${y}: ${t} decisions (government won ${r.g}, government lost ${r.i}, not coded ${r.u})"><div style="height:${h}%;display:flex;flex-direction:column;justify-content:flex-end"><i style="height:${t?r.u/t*100:0}%;background:${UNK}"></i><i style="height:${t?r.i/t*100:0}%;background:${IND}"></i><i style="height:${t?r.g/t*100:0}%;background:${GOV}"></i></div></div>`}).join('')}</div><div class="ix-yl">${allY.map((y,i)=>`<span>${allY.length>14&&i%2?'':(allY.length>26?y.slice(2):y)}</span>`).join('')}</div>`:'<div class="ix-empty">No dated decisions.</div>';
const decOut=tally(dec,'decision_outcome','Not recorded').slice(0,6),types=tally(dec,'case_type','Not recorded').slice(0,6),parties=tally(dec,'government_party').slice(0,5);
const mins=(d.filter&&d.filter.available_ministers)||[];const mostCited=dec.slice().sort((a,b)=>(b.cited_by_cases||0)-(a.cited_by_cases||0))[0];
const rate=classified?Math.round(gw/classified*1000)/10:null;
$('jpMain').innerHTML=`<div class="ix-hero"><div class="ix-eyebrow">${E(p.primary_court||'Court not recorded')}${first?` · active ${first}${last!==first?' to '+last:''} in this library`:''}</div><h3>${E(jpName(p.display_name))}</h3>
<p class="ix-summary">${N(dec.length)} decisions in this view${jp.minister?` for the Minister "${E(jp.minister)}"`:''}. ${classified?`Of the ${N(classified)} where the outcome is coded, the government succeeded in ${N(gw)} (${rate}%) and the individual in ${N(iw)}.`:'Outcomes have not been coded for these decisions.'}${busiest?` Busiest year: ${E(busiest.year)} with ${N(busiest.decisions)} decisions.`:''}${mostCited&&mostCited.cited_by_cases>0?` Most cited: ${E(mostCited.title)} (${N(mostCited.cited_by_cases)} citing decisions).`:''}</p>
${alias.length?`<details class="jp-alias"><summary>${alias.length} name variant${alias.length>1?'s':''} merged into this profile</summary>${alias.map(a=>`<span class="ix-pill" style="margin:4px 4px 0 0">${E(a)}</span>`).join('')}</details>`:''}
${mins.length?`<div class="ix-filters" style="margin:12px 0 0"><label for="jpMin" style="font-size:12px;color:var(--muted)">Minister</label><select id="jpMin"><option value="">Any</option>${mins.map(m=>`<option value="${E(m)}" ${m===jp.minister?'selected':''}>${E(m)}</option>`).join('')}</select></div>`:''}</div>
<div class="ix-tiles"><div class="ix-tile"><div class="v">${N(dec.length)}</div><div class="l">Decisions</div><div class="s">${N(Number(o.all_linked||dec.length))} linked overall</div></div>
<div class="ix-tile"><div class="v">${rate==null?'n/a':rate+'%'}</div><div class="l">Government success</div><div class="s">${N(classified)} coded decisions</div></div>
<div class="ix-tile"><div class="v">${classified?Math.round(iw/classified*1000)/10+'%':'n/a'}</div><div class="l">Individual success</div><div class="s">${N(iw)} decisions</div></div>
<div class="ix-tile"><div class="v">${busiest?E(busiest.year):'n/a'}</div><div class="l">Busiest year</div><div class="s">${busiest?N(busiest.decisions)+' decisions':''}</div></div></div>
<div class="ix-grid"><div class="ix-card wide"><h4>Decisions by year</h4><p class="ix-note">Each bar is one year. Colour shows who succeeded where the outcome is coded.</p>${chart}<div style="margin-top:10px">${split([{label:'Government won',value:gw,color:GOV},{label:'Government lost',value:iw,color:IND},{label:'Not coded',value:un,color:UNK}],'rate')}</div></div>
${keyCard(dec)}<div class="ix-card"><h4>How decisions ended</h4><p class="ix-note">Outcome of the decision itself, such as allowed or dismissed.</p>${bars(decOut.map(([k,v])=>({label:k,value:v,text:N(v)+' · '+Math.round(v/Math.max(dec.length,1)*100)+'%'})))||'<div class="ix-empty">None recorded.</div>'}</div>
<div class="ix-card"><h4>Types of matter</h4><p class="ix-note">Judicial review, appeal and other proceeding types.</p>${bars(types.map(([k,v])=>({label:k,value:v,text:N(v)})),'var(--blue)')||'<div class="ix-empty">None recorded.</div>'}</div>
<div class="ix-card wide" id="jpDecCard"></div><div class="ix-card wide" id="jpIssuesCard"><h4>Outcome patterns by issue</h4><p class="ix-note">Outcome method: government outcome “won” = Minister win, “lost” = applicant win, “mixed” = other; undetermined, unrecognized, and missing values are unclassified, and percentages use all issue decisions, including unclassified.</p><div id="jpIssuesContent"></div></div></div>
<div class="ix-note-strip">Outcome coding is rule-based and has known errors, so treat percentages as a guide and open the decision to confirm.</div>`;
jpRenderDecisions();jpRenderIssues()}
function jpRenderDecisions(){const card=$('jpDecCard');if(!card||!jp.data)return;const all=jp.data.decisions||[],years=[...new Set(all.map(x=>yearOf(x.date)).filter(Boolean))].sort().reverse();
const o=jp.f.outcome,q=jp.f.q.toLowerCase(),y=jp.f.year,cites=all.some(x=>x.cited_by_cases!=null);
const rows=all.filter(x=>(!o||(o==='won'?x.government_outcome==='won':o==='lost'?x.government_outcome==='lost':x.government_outcome!=='won'&&x.government_outcome!=='lost'))&&(!y||yearOf(x.date)===y)&&(!q||((x.title||'')+' '+(x.citation||'')).toLowerCase().includes(q))).sort((a,b)=>jp.f.sort==='cited'?((b.cited_by_cases||0)-(a.cited_by_cases||0)):String(b.date||'').localeCompare(String(a.date||'')));
const chip=(v,l)=>`<button class="ix-chip ${jp.f.outcome===v?'on':''}" data-jpf="${v}">${l}</button>`;
card.innerHTML=`<h4>Decisions</h4><p class="ix-note">${N(rows.length)} of ${N(all.length)} shown, ${jp.f.sort==='cited'?'most cited first':'newest first'}.</p><div class="ix-filters"><input id="jpFq" type="search" placeholder="Filter by case name or citation" value="${E(jp.f.q)}">${cites?`<select id="jpFs"><option value="">Newest first</option><option value="cited" ${jp.f.sort==='cited'?'selected':''}>Most cited first</option></select>`:''}<select id="jpFy"><option value="">All years</option>${years.map(v=>`<option ${v===y?'selected':''}>${v}</option>`).join('')}</select>${chip('','All')}${chip('won','Government won')}${chip('lost','Individual won')}${chip('none','Not coded')}</div>
<div class="ix-list">${rows.slice(0,jp.shown).map(x=>`<div class="ix-row"><div><div class="tt">${E(x.title||'Untitled decision')}</div><div class="mm"><span>${E(x.citation||'No citation')}</span><span>${E(x.date||'')}</span>${outcomePill(x.government_outcome)}${x.decision_outcome?`<span class="ix-pill">${E(x.decision_outcome)}</span>`:''}${x.case_type?`<span>${E(x.case_type)}</span>`:''}${x.cited_by_cases?`<span><b>${N(x.cited_by_cases)}</b> citing</span>`:''}</div></div><button class="ix-btn ix-open" data-open="${x.case_id}">Open</button></div>`).join('')||'<div class="ix-empty"><b>No decisions match</b>Clear a filter to see more.</div>'}</div>${rows.length>jp.shown?`<button class="ix-btn ix-more" data-jpmore="1">Show ${Math.min(30,rows.length-jp.shown)} more</button>`:''}`;}
const jpIssueCategories=[['minister_win','Minister win'],['applicant_win','Applicant win'],['other','Other'],['unclassified','Unclassified']];
function jpIssueOutcomeCell(outcome){const count=Number(outcome?.count||0),denominator=Number(outcome?.denominator||0),percent=outcome?.percent;return `<td title="${N(count)} of ${N(denominator)} issue decisions, including unclassified">${N(count)} / ${N(denominator)} · ${percent==null?'n/a':Number(percent).toFixed(1)+'%'}</td>`}
function jpRenderIssues(){const target=$('jpIssuesContent');if(!target)return;if(jp.issueLoading){target.innerHTML='<div class="ix-load">Loading issue outcomes...</div>';return}if(jp.issueError){target.innerHTML=`<div class="ix-empty"><b>Issue outcomes unavailable</b>${E(jp.issueError)} <button class="ix-btn" data-jp-issues>Retry</button></div>`;return}if(!jp.issueData){target.innerHTML='<button type="button" class="ix-btn" data-jp-issues>Load issue outcomes</button>';return}
const data=jp.issueData,hidden=Number(data.hidden_issue_count||0),minimum=N(data.metadata?.minimum_decisions_per_visible_issue||10),rows=(data.issues||[]).map(item=>{const judge=item.judge||{},baseline=item.federal_court_baseline||{},judgeOutcomes=judge.outcomes||{},baselineOutcomes=baseline.outcomes||{};return `<tr><th scope="row">${E(item.issue)}</th><td>${N(judge.decisions?.count)} / ${N(judge.decisions?.denominator)}</td>${jpIssueCategories.map(([key])=>jpIssueOutcomeCell(judgeOutcomes[key])).join('')}<td>${N(baseline.decisions?.count)} / ${N(baseline.decisions?.denominator)}</td>${jpIssueCategories.map(([key])=>jpIssueOutcomeCell(baselineOutcomes[key])).join('')}</tr>`}).join('');
target.innerHTML=`<p class="ix-note jp-issue-scope">At least ${minimum} distinct decisions are required per judge issue; ${N(hidden)} issue${hidden===1?'':'s'} hidden (each has fewer than ${minimum} decisions). Federal Court baseline uses the stored court labels FC, Federal Court, or Federal Court of Canada.</p>${rows?`<div class="jp-issue-table-wrap"><table class="jp-issue-table"><thead><tr><th scope="col" rowspan="2">Recorded issue</th><th scope="col" rowspan="2">Judge decisions / linked</th><th scope="colgroup" colspan="4">Judge issue outcomes</th><th scope="col" rowspan="2">Federal Court decisions / courtwide</th><th scope="colgroup" colspan="4">Federal Court issue outcomes</th></tr><tr>${jpIssueCategories.map(([,label])=>`<th scope="col">${label}</th>`).join('')}${jpIssueCategories.map(([,label])=>`<th scope="col">${label}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`:'<div class="ix-empty">No recorded issues meet the minimum threshold.</div>'}${data.metadata?.interpretation?`<p class="ix-note">${E(data.metadata.interpretation)}</p>`:''}`}
async function jpLoadIssues(){if(!jp.slug||jp.issueLoading||jp.issueData)return;const slug=jp.slug,request=++jp.issueRequest;jp.issueLoading=true;jp.issueError='';jpRenderIssues();try{const data=await getJSON(`/api/judge-profiles/${encodeURIComponent(slug)}/issues`);if(jp.slug!==slug||jp.issueRequest!==request)return;jp.issueData=data}catch(error){if(jp.slug!==slug||jp.issueRequest!==request)return;jp.issueError=error.message}finally{if(jp.slug===slug&&jp.issueRequest===request){jp.issueLoading=false;jpRenderIssues()}}}
function jpMainClick(e){const issueButton=e.target.closest('[data-jp-issues]');if(issueButton){jpLoadIssues();return}const f=e.target.closest('[data-jpf]');if(f){jp.f.outcome=f.dataset.jpf;jp.shown=20;jpRenderDecisions();return}const m=e.target.closest('[data-jpmore]');if(m){jp.shown+=30;jpRenderDecisions();return}const op=e.target.closest('[data-open]');if(op)openCase(op.dataset.open)}

/* ---------------- Citation intelligence ---------------- */
const ci={id:null,data:null,evPage:1,evRows:[],evTotal:0};
function ciShell(){const panel=$('citationIntelligencePanel');if(!panel||$('ciApp'))return;panel.insertAdjacentHTML('beforeend',`<div id="ciApp"><div class="ix-head"><div><div class="ix-eyebrow">Authority analysis</div><h2>Citation Intelligence</h2><p>Look up any case to see how much it is cited, when, by whom, with what results, and which other authorities travel with it.</p></div></div><div class="ix-search"><input id="ciSearch" type="search" placeholder="Search by case name or citation, e.g. Vavilov or 2019 SCC 65" autocomplete="off" aria-label="Find a case"><div class="ix-suggest" id="ciSuggest" hidden></div></div><div class="ix-chips" id="ciExamples" style="margin-bottom:14px"><span style="font-size:12px;color:var(--muted)">Try</span>${['Vavilov','Dunsmuir','Baker v. Canada','Mugesera','Singh v. Minister'].map(x=>`<button class="ix-chip" data-ex="${E(x)}">${E(x)}</button>`).join('')}</div><div id="ciBody"><div class="ix-empty"><b>Start with a case</b>Search above, then open its citation snapshot.</div></div></div>`);
const input=$('ciSearch'),box=$('ciSuggest');let items=[],idx=-1;
const render=()=>{box.hidden=!items.length&&!input.value.trim();box.innerHTML=items.length?items.map((c,i)=>`<button type="button" class="ix-sg ${i===idx?'on':''}" data-pick="${c.case_id}"><span><b>${E(c.title)}</b><small>${E([c.citation,c.court,yearOf(c.date)].filter(Boolean).join(' · '))}</small></span><span class="ix-cnt"><strong>${N(c.in_degree)}</strong>cited by</span></button>`).join(''):(input.value.trim().length>1?'<div class="ix-load">No cases found. Try fewer words or a citation.</div>':'')};
const run=debounce(async()=>{const q=input.value.trim();if(q.length<2){items=[];render();return}try{const rows=await getJSON('/api/citation-intelligence/search?limit=30&q='+encodeURIComponent(q));if(q!==input.value.trim())return;items=rows.sort((a,b)=>(b.in_degree||0)-(a.in_degree||0)).slice(0,10);idx=-1;render()}catch(err){box.hidden=false;box.innerHTML=`<div class="ix-load">${E(err.message)}</div>`}},220);
input.addEventListener('input',run);
input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){idx=Math.min(items.length-1,idx+1);render();e.preventDefault()}else if(e.key==='ArrowUp'){idx=Math.max(0,idx-1);render();e.preventDefault()}else if(e.key==='Enter'){const c=items[idx>=0?idx:0];if(c){ciOpen(c.case_id);box.hidden=true}else run()}else if(e.key==='Escape')box.hidden=true});
box.addEventListener('click',e=>{const b=e.target.closest('[data-pick]');if(b){box.hidden=true;ciOpen(Number(b.dataset.pick))}});
document.addEventListener('click',e=>{if(!e.target.closest('.ix-search'))box.hidden=true});
$('ciExamples').addEventListener('click',e=>{const b=e.target.closest('[data-ex]');if(!b)return;input.value=b.dataset.ex;input.focus();run()});
$('ciBody').addEventListener('click',ciBodyClick)}
async function ciInit(){ciShell();const id=new URLSearchParams(location.search).get('case_id');if(id&&Number(id)!==ci.id)ciOpen(Number(id))}
async function ciOpen(id){ciShell();ci.id=id;ci.evPage=1;ci.evRows=[];setParams(p=>p.set('case_id',id));if(typeof ciState!=='undefined'){ciState.caseId=String(id)}
const body=$('ciBody');$('citationIntelligencePanel').classList.remove('ix-legacy');body.innerHTML='<div class="ix-load">Loading citation snapshot...</div>';const base='/api/citation-intelligence/'+id+'/';
const get=async p=>{try{return await getJSON(base+p)}catch(e){return []}};
ci.data={ov:null,tl:null,oc:null,co:null,ju:null,st:null,cp:null,ready:{}};
const part=(key,path,fn)=>get(path).then(v=>{if(ci.id!==id)return;fn(v);ci.data.ready[key]=true;ciRender()});
part('ov','overview',v=>{ci.data.ov=Array.isArray(v)?null:v;if(!ci.data.ov)ci.data.ov={title:'This case could not be loaded',unique_citing_cases:0}});
part('tl','timeline',v=>ci.data.tl=v);part('oc','outcomes',v=>ci.data.oc=Array.isArray(v)?null:v);part('co','courts',v=>ci.data.co=v);
part('ju','judges',v=>ci.data.ju=v);part('st','statutes',v=>ci.data.st=v);part('cp','companions',v=>ci.data.cp=v);
part('ev','table?page=1&page_size=100',v=>{ci.evRows=(v&&v.rows)||[];ci.evTotal=(v&&v.total)||0})}
function ciRender(){const D=ci.data,body=$('ciBody'),rd=D.ready,L='<div class="ix-load">Loading...</div>';if(!D.ov){body.innerHTML='<div class="ix-load">Loading citation snapshot...</div>';return}const ov=D.ov,tl=D.tl||[],oc=D.oc,co=D.co||[],ju=D.ju||[],st=D.st||[],cp=D.cp||[];
const cited=Number(ov.unique_citing_cases||0),occ=Number(ov.total_occurrences||0);
if(!cited){body.innerHTML=`<div class="ix-hero"><div class="ix-eyebrow">${E(ov.court||'')}</div><h3>${E(ov.title)}</h3><div class="ix-sub">${E([ov.citation,ov.date].filter(Boolean).join(' · '))}</div><p class="ix-summary">No other decision in the library cites this case yet.</p><div class="ix-actions"><button class="ix-btn primary" data-open="${ci.id}">Open decision</button></div></div>`;return}
const first=ov.first_citation_date,last=ov.most_recent_citation_date;
const topCourt=co[0],topStat=st.find(s=>s.provision),goodJudges=ju.filter(j=>!junkName(j.judge));
const outTot=oc?Number(oc.total_cases||0):0;
const sum=[`Cited by <b>${N(cited)}</b> decision${cited>1?'s':''} (${N(occ)} mention${occ>1?'s':''}${Number(ov.max_mentions_in_single_case)>1?`, up to ${N(ov.max_mentions_in_single_case)} in one decision`:''}), from ${E(first||'an unknown date')} to ${E(last||'an unknown date')}.`];
if(topCourt)sum.push(`Mostly cited in ${E(topCourt.court)} (${Math.round(topCourt.pct||0)}%).`);
if(oc&&outTot)sum.push(`In citing decisions the government won ${Math.round(oc.government_win_pct||0)}% and lost ${Math.round(oc.government_loss_pct||0)}%.`);
if(cp[0])sum.push(`Most often cited alongside <b>${E(cp[0].authority.title)}</b>.`);
const secs=[['ciTime','Over time'],['ciOut','Outcomes'],['ciWho','Courts and judges'],['ciLaw','Statutes'],['ciCo','Cited together'],['ciEv','Where it is cited'],['ciNet','Network']];
const years=tl.map(t=>Number(t.year)),allY=[];if(years.length)for(let y=Math.min(...years);y<=Math.max(...years);y++)allY.push(y);
const ym={};tl.forEach(t=>ym[t.year]=t);const maxC=Math.max(...tl.map(t=>Number(t.citing_cases)||0),1);
const chart=allY.length?`<div class="ix-years">${allY.map(y=>{const t=ym[y]||{citing_cases:0,occurrences:0};return `<div class="yc" title="${y}: ${N(t.citing_cases)} citing decisions, ${N(t.occurrences)} mentions"><i style="height:${(Number(t.citing_cases)||0)/maxC*100}%;background:var(--blue);border-radius:2px 2px 0 0;min-height:${t.citing_cases?2:0}px"></i></div>`}).join('')}</div><div class="ix-yl">${allY.map((y,i)=>`<span>${allY.length>14&&i%2?'':(allY.length>26?String(y).slice(2):y)}</span>`).join('')}</div>`:(rd.tl?'<div class="ix-empty">No yearly data.</div>':L);
const peak=tl.slice().sort((a,b)=>b.citing_cases-a.citing_cases)[0];
body.innerHTML=`<div class="ix-hero"><div class="ix-eyebrow">${E(ov.court||'')}${ov.in_degree?` · cited by ${N(ov.in_degree)} in all`:''}</div><h3>${E(ov.title)}</h3><div class="ix-sub"><span>${E(ov.citation||'No neutral citation')}</span><span>${E(ov.date||'')}</span></div><p class="ix-summary">${sum.join(' ')}</p><div class="ix-actions"><button class="ix-btn primary" data-open="${ci.id}">Open decision</button><button class="ix-btn" data-ci-ev="1">See where it is cited</button></div></div>
<div class="ix-tiles"><div class="ix-tile"><div class="v">${N(cited)}</div><div class="l">Citing decisions</div></div><div class="ix-tile"><div class="v">${N(occ)}</div><div class="l">Total mentions</div><div class="s">${E(ov.avg_mentions_per_case||'')} per decision</div></div><div class="ix-tile"><div class="v">${peak?E(peak.year):'n/a'}</div><div class="l">Peak year</div><div class="s">${peak?N(peak.citing_cases)+' citing decisions':''}</div></div><div class="ix-tile"><div class="v">${oc&&outTot?Math.round(oc.government_win_pct||0)+'%':'n/a'}</div><div class="l">Government won</div><div class="s">in citing decisions</div></div></div>
<div class="ix-nav">${secs.map(s=>`<button class="ix-chip" data-ci-jump="${s[0]}">${s[1]}</button>`).join('')}</div>
<div class="ix-grid"><div class="ix-card wide" id="ciTime"><h4>Citing decisions by year</h4><p class="ix-note">How many decisions cited this authority each year. Hover a bar for exact numbers.</p>${chart}</div>
<div class="ix-card" id="ciOut"><h4>Outcomes in citing decisions</h4><p class="ix-note">Who won in the ${N(outTot)} decisions that cite this case, where the outcome is coded.</p>${oc&&outTot?split([{label:'Government won',value:oc.government_win||0,color:GOV},{label:'Government lost',value:oc.government_loss||0,color:IND},{label:'Mixed',value:oc.mixed||0,color:MIX},{label:'Not coded',value:oc.unknown||0,color:UNK}],'rate'):(rd.oc?'<div class="ix-empty">No outcome data.</div>':L)}</div>
<div class="ix-card" id="ciWho"><h4>Courts that cite it</h4><p class="ix-note">Share of citing decisions by court.</p>${bars(co.map(c=>({label:c.court,value:c.case_count,text:N(c.case_count)+' · '+Math.round(c.pct||0)+'%'})),'var(--blue)')||(rd.co?'<div class="ix-empty">No court data.</div>':L)}<h4 style="margin-top:16px">Judges who cite it</h4><p class="ix-note">Judges whose decisions cite this case most.</p>${bars(goodJudges.slice(0,6).map(j=>({label:j.judge,value:j.case_count,text:N(j.case_count)+' decision'+(j.case_count>1?'s':'')})))||(rd.ju?'<div class="ix-empty">No judge data.</div>':L)}</div>
<div class="ix-card" id="ciLaw"><h4>Statutes it appears with</h4><p class="ix-note">Provisions most often cited in the same decisions.</p>${bars(st.slice(0,8).map(s=>({label:s.provision,value:s.case_count,text:N(s.case_count)+' decision'+(s.case_count>1?'s':'')})))||(rd.st?'<div class="ix-empty">No statute data.</div>':L)}</div>
<div class="ix-card" id="ciCo"><h4>Often cited together</h4><p class="ix-note">Other authorities that show up in the same citing decisions.</p><div class="ix-list">${cp.slice(0,6).map(c=>`<div class="ix-row"><div><div class="tt">${E(c.authority.title)}</div><div class="mm"><span>${E(c.authority.citation||'')}</span><span>${E(c.authority.court||'')}</span><span>together in ${N(c.shared_citing_cases)} decision${c.shared_citing_cases>1?'s':''}</span></div></div><button class="ix-btn ix-open" data-ci-switch="${c.authority.case_id}">Snapshot</button></div>`).join('')||(rd.cp?'<div class="ix-empty">None found.</div>':L)}</div></div>
<div class="ix-card wide" id="ciEv"></div>
<div class="ix-card wide" id="ciNet"><h4>Network</h4><p class="ix-note">The direct neighbourhood of this case: what cites it and what it cites.</p><button class="ix-btn" data-ci-net="1">Show network view</button></div></div>`;
ciRenderEvidence()}
function ciRenderEvidence(){const card=$('ciEv');if(!card)return;const groups=[],seen={};ci.evRows.forEach(r=>{let g=seen[r.case_id];if(!g){g=seen[r.case_id]={r,texts:[]};groups.push(g)}if(r.citation_text&&!g.texts.includes(r.citation_text))g.texts.push(r.citation_text)});const more=ci.evTotal>ci.evRows.length;
card.innerHTML=`<h4>Where it is cited</h4><p class="ix-note">${N(ci.evTotal)} stored citation${ci.evTotal===1?'':'s'}, grouped by citing decision. Quotes show the citation as written.</p><div class="ix-list">${groups.map(({r,texts})=>`<div class="ix-row"><div><div class="tt">${E(r.case_title)}</div><div class="mm"><span>${E(r.case_citation||'')}</span><span>${E(r.date||'')}</span>${junkName(r.judge)?'':`<span>${E(r.judge)}</span>`}${outcomePill(r.gov_outcome)}${r.mention_count>1?`<span>${N(r.mention_count)} mentions</span>`:''}</div></div><button class="ix-btn ix-open" data-open="${r.case_id}">Open</button>${texts.slice(0,2).map(t=>`<q>${E(t)}</q>`).join('')}${texts.length>2?`<q>+ ${texts.length-2} more citation${texts.length>3?'s':''} in this decision</q>`:''}</div>`).join('')||(ci.data.ready.ev?'<div class="ix-empty">None stored.</div>':'<div class="ix-load">Loading...</div>')}</div>${more?`<button class="ix-btn ix-more" data-ci-more="1">Show more</button>`:''}`}
async function ciBodyClick(e){const t=e.target.closest('[data-open],[data-ci-switch],[data-ci-jump],[data-ci-ev],[data-ci-more],[data-ci-net]');if(!t)return;
if(t.dataset.open)return openCase(t.dataset.open);
if(t.dataset.ciSwitch){window.scrollTo({top:0,behavior:'smooth'});return ciOpen(Number(t.dataset.ciSwitch))}
if(t.dataset.ciJump||t.dataset.ciEv){const el=$(t.dataset.ciJump||'ciEv');if(el)el.scrollIntoView({behavior:'smooth',block:'start'});return}
if(t.dataset.ciMore){t.disabled=true;t.textContent='Loading...';try{const next=ci.evPage+1,d=await getJSON('/api/citation-intelligence/'+ci.id+'/table?page='+next+'&page_size=100');ci.evPage=next;ci.evRows=ci.evRows.concat(d.rows||[]);ci.evTotal=d.total||ci.evTotal}catch(err){}ciRenderEvidence();return}
if(t.dataset.ciNet){const panel=$('citationIntelligencePanel');panel.classList.add('ix-legacy');if(typeof loadCitationNeighborhood==='function')loadCitationNeighborhood();const back=document.createElement('button');back.className='ix-btn';back.textContent='Back to snapshot';back.style.margin='0 0 10px';back.onclick=()=>{panel.classList.remove('ix-legacy');back.remove()};$('citationIntelligenceContent').before(back)}}

/* ---------------- Activation ---------------- */
function check(){const ciP=$('citationIntelligencePanel'),jpP=$('judgeProfilePanel');if(ciP&&!ciP.hidden)ciInit();if(jpP&&!jpP.hidden)jpInit()}
['citationIntelligencePanel','judgeProfilePanel'].forEach(id=>{const p=$(id);if(p)new MutationObserver(check).observe(p,{attributes:true,attributeFilter:['hidden']})});
window.addEventListener('popstate',check);
check();
})();
