from __future__ import annotations


def case_reader_html() -> str:
	return r"""<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
	<title>Legacy Case Reader | AI CaseLibrary</title>
	<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&family=Newsreader:opsz,wght@6..72,600;6..72,700&display=swap" rel="stylesheet">
	<script src="https://unpkg.com/lucide@0.468.0/dist/umd/lucide.min.js"></script>
	<style>
		:root{--ink:#202522;--muted:#69726d;--paper:#f1efe8;--surface:#fffef9;--surface-2:#f8f6ef;--line:#d8d5ca;--rust:#a4412b;--teal:#176c68;--blue:#315d8d;--gold:#c28e2d;--olive:#62754d;--cite-bg:#f5ece0;--cite-line:#d68f52;--tag-bg:#e9f4f2;--tag-line:#3e8f88;--shadow:0 10px 28px rgba(32,37,34,.07)}
		*{box-sizing:border-box}html,body{max-width:100%;overflow-x:hidden}body{margin:0;min-height:100vh;color:var(--ink);font-family:"IBM Plex Sans",sans-serif;background:var(--paper);background-image:linear-gradient(rgba(32,37,34,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(32,37,34,.035) 1px,transparent 1px);background-size:26px 26px}button,input{font:inherit}button{cursor:pointer}
		.top{height:68px;display:flex;align-items:center;justify-content:space-between;gap:20px;padding:0 24px;border-bottom:1px solid var(--line);background:rgba(255,254,249,.96)}.brand{display:flex;align-items:baseline;gap:13px}.brand h1{margin:0;font:700 28px/1 "Newsreader",serif}.brand span{color:var(--muted);font-size:12px}.nav{display:flex;gap:5px}.nav a{display:flex;align-items:center;gap:5px;padding:7px 9px;border-radius:5px;color:var(--muted);font-size:10px;text-decoration:none}.nav a.active{background:var(--ink);color:white}.nav a:hover{color:var(--teal)}.nav i{width:14px;height:14px}
		.shell{display:grid;grid-template-columns:310px minmax(0,1fr) 360px;height:calc(100vh - 68px)}.left,.center,.right{min-width:0;min-height:0}.left,.right{background:rgba(255,254,249,.93)}.left{border-right:1px solid var(--line)}.right{border-left:1px solid var(--line)}
		.head{padding:18px;border-bottom:1px solid var(--line)}h2{margin:0;font:600 21px/1.15 "Newsreader",serif}.search{position:relative;margin-top:12px}.search i{position:absolute;left:11px;top:11px;width:16px;color:var(--muted)}.search input{width:100%;height:39px;padding:8px 10px 8px 36px;border:1px solid var(--line);border-radius:5px;background:var(--surface);outline:0}.search input:focus{border-color:var(--teal)}.hint{margin:9px 0 0;color:var(--muted);font-size:10px}.results{height:calc(100% - 126px);overflow:auto}.result{width:100%;padding:13px 17px;border:0;border-bottom:1px solid #e9e6dd;background:transparent;text-align:left;color:var(--ink)}.result:hover,.result.active{background:#edf3f0}.result strong{display:block;font-size:12px;line-height:1.35}.result small{display:block;margin-top:4px;color:var(--muted);font-size:10px}.empty{padding:24px 18px;color:var(--muted);font-size:11px;line-height:1.55}
		.center{overflow:auto;background:rgba(255,254,249,.66)}.document{max-width:1080px;margin:0 auto;padding:26px clamp(18px,4vw,48px) 72px}.document-header{padding:20px;border:1px solid var(--line);border-radius:5px;background:rgba(255,254,249,.94);box-shadow:none}.eyebrow{color:var(--rust);font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.document h2{margin:9px 0 10px;font-size:clamp(28px,4vw,46px);line-height:1.04}.document-summary{max-width:76ch;margin:0 0 14px;color:var(--ink);font-size:14px;line-height:1.7}.meta{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:12px}.meta span,.meta a{padding:5px 8px;border:1px solid var(--line);border-radius:4px;background:var(--surface);color:var(--muted);font-size:10px;text-decoration:none}.meta a{color:var(--blue)}.stats{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0 0}.stat{display:inline-flex;align-items:baseline;gap:6px;padding:7px 9px;border:1px solid var(--line);border-radius:4px;background:var(--surface)}.stat strong{font-size:13px;color:var(--ink)}.stat span{color:var(--muted);font-size:10px}.quality-strip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px;margin-top:12px}.quality-card{padding:9px 10px;border:1px solid var(--line);border-radius:4px;background:var(--surface)}.quality-card strong{display:block;font-size:15px;line-height:1;color:var(--ink)}.quality-card span{display:block;margin-top:5px;font-size:10px;color:var(--muted);line-height:1.35}.quality-pill{display:inline-flex;align-items:center;padding:3px 7px;border-radius:4px;border:1px solid var(--line);font-size:9px;letter-spacing:.06em;text-transform:uppercase;font-weight:700;background:#f3f2ec;color:#5b645f}.quality-pill.strong{background:#e8f4ef;border-color:#76af9c;color:#1b6958}.quality-pill.watch{background:#fff2e4;border-color:#d19a5f;color:#87511f}.quality-pill.risk{background:#f9e5e3;border-color:#d17e78;color:#8e3027}.citation-stream{display:flex;flex-wrap:wrap;gap:6px;margin-top:14px}.citation-chip{display:inline-flex;align-items:center;max-width:100%;padding:5px 7px;border:1px solid var(--cite-line);border-radius:4px;background:var(--cite-bg);color:var(--ink);font-size:10px;line-height:1.35;text-decoration:none}.citation-chip.warn{border-color:#b06f31;background:#f8efe4}.citation-chip.muted{border-style:dashed;color:var(--muted)}.legend{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 16px}.legend span{display:inline-flex;align-items:center;gap:5px;padding:4px 7px;border:1px solid var(--line);border-radius:4px;background:var(--surface);font-size:10px;color:var(--muted)}.swatch{width:10px;height:10px;border-radius:2px;border:1px solid var(--line)}
		.chunks{display:grid;gap:12px}.chunk{border:1px solid var(--line);border-radius:5px;background:rgba(255,254,249,.92);box-shadow:none;overflow:hidden}.chunk-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:12px 15px;border-bottom:1px solid var(--line);font-size:10px;color:var(--muted);background:#f8f6ef}.chunk-head strong{color:var(--ink);font-size:11px;letter-spacing:.05em;text-transform:uppercase;font-weight:700}.chunk-text{padding:18px 20px;font:17px/1.82 "Newsreader",serif;color:#1a1a1a}.chunk-text p{margin:0 0 1.5em;white-space:pre-wrap;word-wrap:break-word;overflow-wrap:break-word}.chunk-text p:first-child{margin-top:0}.chunk-text p:last-child{margin-bottom:0}.chunk-text mark{position:relative;display:inline-block;padding:2px 5px;border-radius:3px;font-weight:500;transition:all .15s ease;text-decoration:none}.cite-case{background:#e7eef6;box-shadow:inset 0 -1.5px 0 #506ba0;border:1px solid rgba(80,107,160,.2);color:#1a2e4a}.cite-case:hover{background:#dce6f2;box-shadow:inset 0 -2px 0 #3d4f7a;transform:translateY(-1px)}.cite-case::before{content:'';display:inline-block;width:2px;height:0.9em;background:#506ba0;margin-right:3px;border-radius:1px;opacity:.7}.cite-statute{background:#f8f0dc;box-shadow:inset 0 -1.5px 0 #c9804a;border:1px solid rgba(201,128,74,.25);color:#5c3800}.cite-statute:hover{background:#f3ecdc;box-shadow:inset 0 -2px 0 #a36225;transform:translateY(-1px)}.cite-statute::after{content:'§';position:absolute;right:2px;top:-2px;font-size:11px;font-weight:bold;opacity:.4}.chunk-text mark[data-authority]::after{content:attr(data-authority);position:absolute;top:-20px;left:0;background:#2c2c2c;color:#fff;padding:3px 6px;border-radius:3px;font-size:9px;white-space:nowrap;pointer-events:none;opacity:0;transition:opacity .2s}mark:hover[data-authority]::after{opacity:1}
		.placeholder{display:grid;min-height:100%;place-items:center;text-align:center}.placeholder div{max-width:390px}.placeholder i{width:34px;height:34px;color:var(--teal)}.placeholder h2{margin:14px 0 8px;font-size:28px}.placeholder p{margin:0;color:var(--muted);font-size:12px;line-height:1.6}
		.card{padding:16px 15px 14px;border-bottom:1px solid var(--line);background:linear-gradient(180deg,rgba(255,255,255,.88),rgba(248,246,239,.96))}.card .citation{display:block;color:var(--rust);font-size:11px;font-weight:700;letter-spacing:.05em;text-transform:uppercase}.card h3{margin:6px 0 7px;font:600 19px/1.25 "Newsreader",serif}.card p{margin:0;color:var(--muted);font-size:10px;line-height:1.5}.card-summary{margin-top:8px}.card-stats{display:flex;flex-wrap:wrap;gap:6px;margin-top:12px}.card-stats .stat{padding:6px 8px}.quick{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:12px}.quick a{display:flex;align-items:center;justify-content:center;height:33px;border:1px solid var(--line);border-radius:8px;background:var(--surface);color:var(--ink);font-size:10px;text-decoration:none}.quick a:hover{border-color:var(--teal);color:var(--teal)}
		.tabs{display:grid;grid-template-columns:repeat(4,1fr);border-bottom:1px solid var(--line);background:var(--surface-2)}.tab{padding:10px 2px;border:0;background:transparent;color:var(--muted);font-size:9px;letter-spacing:.06em;text-transform:uppercase}.tab.active{color:var(--ink);box-shadow:inset 0 -2px var(--rust)}.panel{height:calc(100% - 188px);overflow:auto}.panel-section{margin:0 0 12px;border-bottom:1px solid var(--line);background:var(--surface)}.panel-section h4{margin:0;padding:12px 14px 8px;color:var(--ink);font-size:10px;letter-spacing:.08em;text-transform:uppercase}.panel-section .section-note{margin:0;padding:0 14px 10px;color:var(--muted);font-size:9px;line-height:1.45}.row{padding:11px 14px;border-top:1px solid #e9e6dd}.row:first-of-type{border-top:0}.row strong{display:block;font-size:11px;line-height:1.35}.row small{display:block;margin-top:3px;color:var(--muted);font-size:9px;line-height:1.45}.row a{display:inline-block;margin-top:6px;color:var(--blue);font-size:10px;text-decoration:none}.badge{display:inline-block;margin:6px 4px 0 0;padding:2px 5px;border-radius:3px;background:#eee8d9;color:#66521f;font-size:9px}.field{display:grid;grid-template-columns:100px 1fr;gap:8px;align-items:start}.field b{font-size:9px;color:var(--muted);text-transform:uppercase}.field span{font-size:10px;word-break:break-word}.metric-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;padding:0 14px 12px}.metric{padding:8px 10px;border:1px solid var(--line);border-radius:10px;background:var(--surface)}.metric strong{display:block;color:var(--ink);font-size:13px}.metric span{display:block;margin-top:2px;color:var(--muted);font-size:9px;line-height:1.4}.qa-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;padding:0 14px 12px}.qa-metric{padding:9px 10px;border:1px solid var(--line);border-radius:10px;background:var(--surface)}.qa-metric strong{display:block;font-size:14px;line-height:1;color:var(--ink)}.qa-metric span{display:block;margin-top:4px;color:var(--muted);font-size:9px;line-height:1.35}
		@media(max-width:1200px){.shell{grid-template-columns:280px minmax(0,1fr)}.right{grid-column:1/-1;height:460px;border-left:0;border-top:1px solid var(--line)}.quality-strip{grid-template-columns:repeat(2,minmax(0,1fr))}}
		@media(max-width:760px){.top{height:auto;min-height:64px;padding:10px 14px}.brand span{display:none}.shell{grid-template-columns:1fr;height:auto}.left{height:300px;border-right:0;border-bottom:1px solid var(--line)}.results{height:174px}.center{min-height:520px}.document{padding:28px 14px 40px}.chunk-text{font-size:15px}.nav a{padding:8px}.nav a span{display:none}}
	</style>
</head>
<body>
	<header class="top"><div class="brand"><h1>ILIT</h1><span>Legacy standalone case reader</span></div><nav class="nav"><a href="/data-explorer"><span>Research</span></a><a href="/citation-map"><i data-lucide="network"></i><span>Citation Map</span></a><a class="active" href="/case-reader"><i data-lucide="book-open"></i><span>Legacy Reader</span></a></nav></header>
	<main class="shell">
		<aside class="left"><div class="head"><h2>Legacy Reader</h2><p class="hint">Retained for reference only. Use the Case Reader opened from main Research search results.</p></div><div id="results" class="results"><div class="empty">Loading cases...</div></div></aside>
		<section id="reader" class="center"><div class="placeholder"><div><i data-lucide="book-open"></i><h2>Select a case to inspect</h2><p>The full decision with chunk and citation overlays will appear here.</p></div></div></section>
		<aside class="right">
			<div id="card" class="card"><span class="citation">No selection</span><h3>Case details</h3><p>Pick a case from search to inspect fields, citations, tags, and sources.</p></div>
			<div class="tabs" style="grid-template-columns:repeat(7,1fr)"><button class="tab active" data-tab="fields">Fields</button><button class="tab" data-tab="citations">Citations</button><button class="tab" data-tab="qa">Info</button><button class="tab" data-tab="intel">Intel</button><button class="tab" data-tab="activity">Activity</button><button class="tab" data-tab="tags">Tags</button><button class="tab" data-tab="acts">Acts / Regs</button></div>
			<div id="panel" class="panel"><div class="empty">No results yet.</div></div>
		</aside>
	</main>
	<script>
		const state={timer:null,selected:null,tab:'fields',data:null};
		const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
		const fmt=v=>new Intl.NumberFormat('en-CA').format(Number(v||0));
		const toDate=v=>v?new Date(v).toLocaleDateString('en-CA'):'-';
		const escRe=v=>String(v).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
		const NOISY_ACRONYMS=new Set(['EN','FR','THE','AND','FOR','WITH','FROM']);
		const METADATA_KEYS=new Set(['imm_number','decision_date','decision_date_written','decision_date_text','location','judge','respondent','country','case_number','court_type','docket','neutral_citation','style_of_cause','place_of_hearing','date_of_hearing','counsel','solicitor','solicitors']);
		async function json(url){const response=await fetch(url);if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail||`Request failed: ${response.status}`)}return response.json()}
		function renderResults(rows){const box=document.getElementById('results');box.innerHTML=rows.map(item=>`<button class="result ${item.case_id===state.selected?'active':''}" data-id="${item.case_id}"><strong>${esc(item.title)}</strong><small>${esc(item.citation||'No neutral citation')} · ${esc(item.court)} · ${esc(item.date)}</small></button>`).join('')||'<div class="empty">No matching cases.</div>';box.querySelectorAll('button').forEach(button=>button.onclick=()=>openCase(+button.dataset.id))}
		async function loadReviewList(){renderResults(await json('/case-reader/cases?limit=300'))}
		function tagNeedles(tags){const needles=[];for(const tag of(tags||[])){const value=String(tag.value||'').trim(),evidence=String(tag.evidence||'').trim();if(value){const normalized=value.replace(/^irpa_s_/i,'').replace(/^irpr_s_/i,'').replaceAll('_',' ').trim();if(normalized)needles.push(normalized);if(/^[a-z]{3,8}$/i.test(value))needles.push(value.toUpperCase())}if(evidence){if(evidence.length<=120)needles.push(evidence);for(const m of evidence.matchAll(/\[([A-Z]{3,8})\]/g))needles.push(m[1]);for(const m of evidence.matchAll(/\b[A-Z]{3,8}\b/g))needles.push(m[0])}}
			return [...new Set(needles.map(v=>String(v).trim()).filter(v=>v.length>=3&&v.length<=120).filter(v=>!/^\d+(?:\(\d+\))*$/.test(v)).filter(v=>!/^[A-Z]{2,8}$/.test(v)||!NOISY_ACRONYMS.has(v.toUpperCase())))]
		}
		function metadataNeedles(metaRows){const needles=[];for(const row of(metaRows||[])){const key=String(row.key||'').trim();if(!METADATA_KEYS.has(key))continue;const value=String(row.value||'').trim();if(!value)continue;needles.push(value);if(key==='imm_number'){needles.push(value.replaceAll('-',' '));needles.push(value.replaceAll('-',''))}if(key==='decision_date'||key==='decision_date_text'){const compact=value.replaceAll('-','').replaceAll('/','');needles.push(compact);const pretty=value.replaceAll('/','-');needles.push(pretty)}if(key==='judge'){const noPrefix=value.replace(/^The\s+Honourable\s+/i,'').trim();if(noPrefix)needles.push(noPrefix)}if(key==='respondent'){const compactName=value.replace(/^The\s+/i,'').trim();if(compactName)needles.push(compactName)}}
			return [...new Set(needles.map(v=>String(v).trim()).filter(v=>v.length>=4&&v.length<=180))]
		}
		function displayStatuteLabel(value){const raw=String(value||'').trim();const label=raw.replace(/^irpa_s_/i,'IRPA s. ').replace(/^irpr_s_/i,'IRPR s. ').replace(/^charter_s_/i,'Charter s. ').replace(/^criminal_code_s_/i,'Criminal Code s. ').replaceAll('_',' ');return label||raw}
		function citationSummary(data){const citations=data.citations||[];let resolved=0,unresolved=0,statutes=0;const unique=[];const seen=new Set();for(const row of citations){const label=String(row.target_citation||row.normalized_citation||row.citation_text||'Citation').trim();if(label&&!seen.has(label)){seen.add(label);unique.push(label)}if(row.unresolved)unresolved+=1;else resolved+=1;if(/\b(?:IRPA|IRPR|Charter|Act|Code|Convention|Regulations?)\b/i.test(label))statutes+=1}return{total:citations.length,resolved,unresolved,statutes,unique}}
		function citationChips(data){const rows=data.citations||[];if(!rows.length)return'<span class="citation-chip muted">No citation rows stored for this case.</span>';const seen=new Set();const chips=[];for(const row of rows){const label=String(row.target_citation||row.normalized_citation||row.citation_text||'Citation').trim();if(!label)continue;const key=`${row.target_case_id||'unresolved'}|${label}`;if(seen.has(key))continue;seen.add(key);const cls=/\b(?:IRPA|IRPR|Charter|Act|Code|Convention|Regulations?)\b/i.test(label)?'warn':'';if(row.target_case_id){chips.push(`<a class="citation-chip ${cls}" href="/case-reader?case_id=${row.target_case_id}" title="${esc(label)}">${esc(label)}</a>`)}else{chips.push(`<span class="citation-chip ${cls} muted" title="${esc(label)}">${esc(label)}</span>`)}if(chips.length>=12)break}return chips.join('')||'<span class="citation-chip muted">No citation rows stored for this case.</span>'}
		function qualitySnapshot(data){const summary=citationSummary(data);const total=Math.max(1,summary.total);const unresolvedRate=summary.unresolved/total;const resolutionRate=Math.max(0,Math.min(100,Math.round((summary.resolved/total)*100)));const statuteCoverage=Math.max(0,Math.min(100,Math.round((summary.statutes/Math.max(1,summary.unique.length))*100)));const metaCount=(data.extracted_metadata||[]).length;let verdict='risk';if(unresolvedRate<=0.2)verdict='strong';else if(unresolvedRate<=0.4)verdict='watch';return{summary,resolutionRate,statuteCoverage,metaCount,verdict,unresolvedRate:Math.round(unresolvedRate*100)}}
		function needleRanges(text,needle){const ranges=[];const isAcronym=/^[A-Z]{3,8}$/.test(needle);const pattern=isAcronym?`\\b${escRe(needle)}\\b`:escRe(needle);const regex=new RegExp(pattern,'gi');let match;while((match=regex.exec(text))!==null){ranges.push({start:match.index,end:match.index+match[0].length});if(match.index===regex.lastIndex)regex.lastIndex+=1}return ranges}
		function normalizedText(value){return String(value||'').replace(/\s+/g,' ').trim().toLowerCase()}
		function phraseRanges(text,needle){const clean=String(needle||'').trim();if(!clean)return[];const parts=clean.split(/\s+/).filter(Boolean);if(!parts.length)return[];const pattern=parts.map(part=>escRe(part)).join('\\s+');const regex=new RegExp(pattern,'gi');const ranges=[];let match;while((match=regex.exec(text))!==null){ranges.push({start:match.index,end:match.index+match[0].length});if(match.index===regex.lastIndex)regex.lastIndex+=1}return ranges}
		function citationNeedles(row){const candidates=[];for(const value of [row.citation_text,row.normalized_citation,row.target_citation,row.target_title]){const clean=String(value||'').replace(/\s+/g,' ').trim();if(!clean)continue;candidates.push(clean);const casePart=clean.match(/(.+?\bv\.?\s+[^,;\n]+)(?:,\s*(?:19|20)\d{2}\s+[A-Z]{2,}\s+\d{1,6})?$/i);if(casePart&&casePart[1])candidates.push(casePart[1].trim())}
			const seen=new Set();return candidates.filter(item=>item.length>=4&&item.length<=220).filter(item=>{const key=item.toLowerCase();if(seen.has(key))return false;seen.add(key);return true})
		}
		function findRanges(text,citations){const ranges=[];const seen=new Set();for(const row of citations){const label=String(row.target_citation||row.normalized_citation||row.citation_text||'Citation');const isStatute=/\b(?:IRPA|IRPR|Charter|Act|Code|Regulations?|s\.\s*\d|section\s*\d)\b/i.test(label);const kind=isStatute?'statute':'case';let start=typeof row.offset_start==='number'?Math.max(0,row.offset_start):-1;let end=typeof row.offset_end==='number'?Math.min(text.length,row.offset_end):-1;let valid=false;if(end>start&&start>=0){const slice=text.slice(start,end);const sliceNorm=normalizedText(slice);const citeNorm=normalizedText(row.citation_text||'');if(!citeNorm||sliceNorm===citeNorm||sliceNorm.includes(citeNorm)||citeNorm.includes(sliceNorm))valid=true}
			if(!valid){const hits=[];for(const needle of citationNeedles(row)){for(const hit of phraseRanges(text,needle)){hits.push(hit)}}if(hits.length){if(start>=0){hits.sort((a,b)=>Math.abs(a.start-start)-Math.abs(b.start-start)||a.start-b.start)}else{hits.sort((a,b)=>a.start-b.start)}start=hits[0].start;end=hits[0].end;valid=true}}
			if(!valid||end<=start)continue;const key=`${start}:${end}:${kind}`;if(seen.has(key))continue;seen.add(key);ranges.push({start,end,kind,label,targetParagraph:row.target_paragraph,targetChunkText:row.target_chunk_text,targetTitle:row.target_title})}
			return ranges.sort((a,b)=>a.start-b.start||b.end-a.end||((a.kind==='case')?-1:1));
		}
		function splitSections(text){const markers=[...text.matchAll(/\[(\d+)\]/g)];if(!markers.length)return[{start:0,end:text.length,text,marker:null}];const sections=[];if(markers[0].index>0)sections.push({start:0,end:markers[0].index,text:text.slice(0,markers[0].index),marker:null});for(let i=0;i<markers.length;i+=1){const start=markers[i].index;const markerNum=markers[i][1];const end=i+1<markers.length?markers[i+1].index:text.length;sections.push({start,end,text:text.slice(start,end),marker:markerNum})}return sections.filter(s=>s.text.trim().length>0)}
		function highlightText(text,ranges,chunkCitations){let out='',cursor=0;const rangesByOffset=new Map();for(const r of ranges){const key=`${r.start}:${r.end}`;rangesByOffset.set(key,(rangesByOffset.get(key)||0)+1)}for(const r of ranges){if(r.start<cursor||r.start>=text.length)continue;const end=Math.min(r.end,text.length);if(end<=cursor)continue;out+=esc(text.slice(cursor,r.start));const overlaps=rangesByOffset.get(`${r.start}:${end}`)||1;const preview=r.targetChunkText?`${r.targetTitle||'Linked authority'} · para. ${r.targetParagraph}: ${String(r.targetChunkText).replace(/\s+/g,' ').trim().slice(0,420)}`:'';const authority=preview||(overlaps>1?'multiple':'cited');const cls=r.kind==='statute'?'cite-statute':'cite-case';out+=`<mark class="${cls}" data-authority="${esc(authority)}" title="${esc(r.label)}">${esc(text.slice(r.start,end))}</mark>`;cursor=end}out+=esc(text.slice(cursor));return out}
		function renderDocument(data){const c=data.case;const chunks=[...(data.chunks||[])].sort((a,b)=>a.chunk_index-b.chunk_index);const byChunk=new Map(chunks.map(chunk=>[chunk.id,chunk]));const byChunkCitations=new Map();for(const row of data.citations||[]){if(!row.chunk_id||!byChunk.has(row.chunk_id))continue;const list=byChunkCitations.get(row.chunk_id)||[];list.push(row);byChunkCitations.set(row.chunk_id,list)}
			const quality=qualitySnapshot(data);const stats=quality.summary;const summary=String(c.summary||'').trim();const citationStrip=citationChips(data);const renderedChunks=chunks.map((chunk,index)=>{const citations=byChunkCitations.get(chunk.id)||[];const ranges=findRanges(chunk.text||'',citations);const sections=splitSections(chunk.text||'');const paragraphs=sections.map((section,secIdx)=>{const localRanges=ranges.filter(r=>r.end>section.start&&r.start<section.end).map(r=>({start:Math.max(0,r.start-section.start),end:Math.min(section.end,r.end)-section.start,kind:r.kind,label:r.label,targetParagraph:r.targetParagraph,targetChunkText:r.targetChunkText,targetTitle:r.targetTitle}));const html=highlightText(section.text,localRanges,citations);const markerHtml=section.marker?`<sup style="display:inline-block;margin:0 4px 0 2px;padding:1px 4px;background:rgba(158,67,47,.08);border:1px solid rgba(158,67,47,.2);border-radius:2px;font-size:10px;font-weight:600;color:#9e432f;font-family:'IBM Plex Sans',sans-serif;vertical-align:super">[${section.marker}]</sup>`:'';return `<p>${markerHtml}${html}</p>`}).join('');const heading=chunk.chunk_label||`Chunk ${chunk.chunk_index+1}`;const meta=[chunk.chunk_set||'legacy'];if(typeof chunk.paragraph_start==='number'&&typeof chunk.paragraph_end==='number'){meta.push(`paras ${chunk.paragraph_start}-${chunk.paragraph_end}`)}return `<article class="chunk"><div class="chunk-head"><strong>${esc(heading)}</strong><span>${meta.join(' · ')} · ${fmt(chunk.text_length)} chars · ~${fmt(chunk.token_estimate)} tokens · #${index+1}</span></div><div class="chunk-text">${paragraphs||'<p>No text in this chunk.</p>'}</div></article>`}).join('')||'<div class="empty">No chunked text available for this case.</div>';
			document.title=`${c.title} | Case Info`;
			document.getElementById('reader').innerHTML=`<article class="document"><header class="document-header"><div class="eyebrow">${esc(c.citation||'No neutral citation')}</div><h2>${esc(c.title)}</h2>${summary?`<p class="document-summary">${esc(summary)}</p>`:''}<div class="meta"><span>${esc(c.court)}</span><span>${esc(c.date)}</span>${c.jurisdiction?`<span>${esc(c.jurisdiction)}</span>`:''}${c.source_name?`<span>${esc(c.source_name)}</span>`:''}${c.source_url?`<a href="${esc(c.source_url)}" target="_blank" rel="noreferrer">Original source</a>`:''}<a href="/citation-map?case_id=${c.id}">Open citation map</a><a href="/citation-intelligence?case_id=${c.id}">Open citation intelligence</a></div><div class="stats"><span class="stat"><strong>${fmt(stats.total)}</strong><span>citation rows</span></span><span class="stat"><strong>${fmt(stats.unique.length)}</strong><span>unique citations</span></span><span class="stat"><strong>${fmt(stats.statutes)}</strong><span>statute / law refs</span></span><span class="stat"><strong>${fmt(stats.unresolved)}</strong><span>unresolved</span></span></div><div class="quality-strip"><div class="quality-card"><strong>${quality.resolutionRate}%</strong><span>resolution rate</span></div><div class="quality-card"><strong>${quality.statuteCoverage}%</strong><span>statute-density of unique citations</span></div><div class="quality-card"><strong>${fmt(quality.metaCount)}</strong><span>extracted metadata fields</span></div><div class="quality-card"><span class="quality-pill ${quality.verdict}">${quality.verdict}</span><span>${quality.unresolvedRate}% unresolved rows</span></div></div><div class="citation-stream">${citationStrip}</div></header><div class="legend"><span title="Case law references with distinct blue highlights; hover to see citation details"><i class="swatch" style="background:linear-gradient(135deg,#e1eaf6,#dce6f2);border:1px solid rgba(80,107,160,.2)"></i>Case law citation</span><span title="Statute and legislative references with distinct gold highlights; § symbol indicates law reference"><i class="swatch" style="background:linear-gradient(135deg,#fef9f2,#fbf5eb);border:1px solid rgba(201,128,74,.25)"></i>Statute / regulation</span><span title="Paragraph numbering aids navigation through text structure; hover for context">[#] Numbered paragraphs</span><span>Hover citations for more details · Click to navigate</span></div><section class="chunks">${renderedChunks}</section></article>`;
		}
		function val(value){if(value===null||value===undefined||value==='')return '-';if(Array.isArray(value))return value.join(', ')||'-';if(typeof value==='object')return esc(JSON.stringify(value));return esc(String(value))}
		function fieldRows(entries){return entries.filter(([,value])=>value!==null&&value!==undefined&&value!=='').map(([key,value])=>`<div class="row"><div class="field"><b>${esc(String(key).replaceAll('_',' '))}</b><span>${val(value)}</span></div></div>`).join('')}
		function renderPanel(){const box=document.getElementById('panel');const d=state.data;if(!d){box.innerHTML='<div class="empty">No results yet.</div>';return}
			if(state.tab==='fields'){const c=d.case;const coreEntries=[['id',c.id],['title',c.title],['citation',c.citation],['secondary_citation',c.secondary_citation],['court',c.court],['date',c.date],['jurisdiction',c.jurisdiction],['language',c.language],['processing_status',c.processing_status]];const sourceEntries=[['source_name',c.source_name],['source_id',c.source_id],['source_type',c.source_type],['dataset_version',c.dataset_version],['upstream_license',c.upstream_license],['scraped_at',c.scraped_at],['full_text_hash',c.full_text_hash]];const derivedEntries=[['citing_cases_count',c.citing_cases_count],['issues',c.issues],['metadata_json',c.metadata_json]];
				const metrics=d.metrics?`<section class="panel-section"><h4>Citation metrics</h4><div class="metric-grid"><div class="metric"><strong>${fmt(d.metrics.in_degree)}</strong><span>incoming citations</span></div><div class="metric"><strong>${fmt(d.metrics.out_degree)}</strong><span>outgoing citations</span></div><div class="metric"><strong>${d.metrics.pagerank?.toFixed(6)??'-'}</strong><span>PageRank</span></div></div><div style="margin-top:10px"><a href="/citation-intelligence?case_id=${d.case.id}" style="display:inline-block;padding:6px 14px;background:#2d6078;color:#fff;font:700 11px Arial,sans-serif;letter-spacing:.5px;text-transform:uppercase;text-decoration:none">View Citation Intelligence ↗</a></div></section>`:'';				const extractedRows=(d.extracted_metadata||[]).map(item=>`<div class="row"><strong>${esc(String(item.key).replaceAll('_',' '))}</strong><small>${esc(item.value)} · ${esc(item.source||'reader_extracted')}</small>${item.evidence?`<div class="badge">${esc(item.evidence)}</div>`:''}</div>`).join('');
				const extractedBlock=extractedRows?`<section class="panel-section"><h4>Extracted metadata</h4><p class="section-note">Derived from decision text and retained with provenance for quick QA.</p>${extractedRows}</section>`:'';
				box.innerHTML=`${metrics}<section class="panel-section"><h4>Core case</h4>${fieldRows(coreEntries)}</section><section class="panel-section"><h4>Source details</h4>${fieldRows(sourceEntries)}</section><section class="panel-section"><h4>Derived record</h4>${fieldRows(derivedEntries)}</section>${extractedBlock}`;
			}else if(state.tab==='citations'){
				box.innerHTML=(d.citations||[]).map(row=>`<div class="row"><strong>${esc(row.target_title||row.citation_text||row.target_citation||'Unresolved citation')}</strong><small>${esc(row.target_citation||row.normalized_citation||'No normalized citation')} · chunk ${row.chunk_id??'-'} · ${row.offset_start??'-'}-${row.offset_end??'-'}</small>${row.target_case_id?`<a href="/case-reader?case_id=${row.target_case_id}">Open target case</a>`:''}${row.provenance?`<div class="badge">${esc(row.provenance)}</div>`:''}${row.unresolved?`<div class="badge">unresolved</div>`:''}</div>`).join('')||'<div class="empty">No citation rows stored for this case.</div>';
			}else if(state.tab==='evidence'){
				const chunks=d.chunks||[],citations=d.citations||[],caseCitations=citations.filter(row=>row.citation_kind!=='statute'),statuteCitations=citations.filter(row=>row.citation_kind==='statute'||/\b(?:IRPA|IRPR|Immigration and Refugee Protection Act|Immigration and Refugee Protection Regulations?)\b/i.test(String(row.normalized_citation||row.citation_text||''))),citedChunkIds=new Set(citations.map(row=>row.chunk_id).filter(Boolean)),textCharacters=chunks.reduce((total,chunk)=>total+Number(chunk.text_length||String(chunk.text||'').length),0),sourceRows=(d.sources||[]).map(source=>`<div class="row"><strong>${esc(source.source_name||source.source_type||'Source')}</strong><small>${esc(source.source_type)} · primary=${source.is_primary?'yes':'no'} · ${toDate(source.scraped_at)}</small>${source.source_url?`<a href="${esc(source.source_url)}" target="_blank" rel="noreferrer">Open source</a>`:''}<div class="badge">${esc(source.source_id||'no source id')}</div></div>`).join('')||'<div class="empty">No provenance records available.</div>';
				box.innerHTML=`<section class="panel-section"><h4>Evidence coverage</h4><p class="section-note">A compact view of how much decision text is available and where the stored evidence points.</p><div class="qa-grid"><div class="qa-metric"><strong>${fmt(chunks.length)}</strong><span>text chunks</span></div><div class="qa-metric"><strong>${fmt(textCharacters)}</strong><span>text characters</span></div><div class="qa-metric"><strong>${fmt(citedChunkIds.size)}</strong><span>chunks with citations</span></div><div class="qa-metric"><strong>${fmt(caseCitations.length+statuteCitations.length)}</strong><span>citation occurrences</span></div><div class="qa-metric"><strong>${fmt(caseCitations.length)}</strong><span>case-law citations</span></div><div class="qa-metric"><strong>${fmt(statuteCitations.length)}</strong><span>statute citations</span></div></div></section><section class="panel-section"><h4>Provenance records</h4>${sourceRows}</section>`;
			}else{
				const quality=qualitySnapshot(d);const stats=quality.summary;const chunks=d.chunks||[],citedChunkIds=new Set((d.citations||[]).map(row=>row.chunk_id).filter(Boolean)),textCharacters=chunks.reduce((total,chunk)=>total+Number(chunk.text_length||String(chunk.text||'').length),0);const unresolvedRows=(d.citations||[]).filter(row=>row.unresolved).slice(0,15);const unresolvedList=unresolvedRows.map(row=>`<div class="row"><strong>${esc(row.citation_text||row.normalized_citation||'Unresolved citation')}</strong><small>${esc(row.normalized_citation||'No normalized form')} · chunk ${row.chunk_id??'-'} · ${row.offset_start??'-'}-${row.offset_end??'-'}</small></div>`).join('')||'<div class="empty">No unresolved citation rows.</div>';
				box.innerHTML=`<section class="panel-section"><h4>Evidence coverage and quality</h4><p class="section-note">Coverage and extraction checks for this case payload.</p><div class="qa-grid"><div class="qa-metric"><strong>${fmt(chunks.length)}</strong><span>text chunks</span></div><div class="qa-metric"><strong>${fmt(textCharacters)}</strong><span>text characters</span></div><div class="qa-metric"><strong>${fmt(citedChunkIds.size)}</strong><span>chunks with citations</span></div><div class="qa-metric"><strong>${fmt(stats.total)}</strong><span>total citation rows</span></div><div class="qa-metric"><strong>${fmt(stats.unresolved)}</strong><span>unresolved rows</span></div><div class="qa-metric"><strong>${quality.unresolvedRate}%</strong><span>unresolved ratio</span></div><div class="qa-metric"><strong>${fmt((d.extracted_metadata||[]).length)}</strong><span>metadata fields</span></div></div></section><section class="panel-section"><h4>Unresolved citations</h4><p class="section-note">Rows that may need extraction refinement.</p>${unresolvedList}</section>`;
			}
		}
		async function loadIntel(){const box=document.getElementById('panel'),caseId=state.selected;if(!caseId){box.innerHTML='<div class="empty">Select a case to inspect citation intelligence.</div>';return}box.innerHTML='<div class="empty">Loading citation intelligence...</div>';try{const [overview,timeline,outcomes,courts,judges,statutes]=await Promise.all([json(`/api/citation-intelligence/${caseId}/overview`),json(`/api/citation-intelligence/${caseId}/timeline`),json(`/api/citation-intelligence/${caseId}/outcomes`),json(`/api/citation-intelligence/${caseId}/courts`),json(`/api/citation-intelligence/${caseId}/judges?limit=6`),json(`/api/citation-intelligence/${caseId}/statutes?limit=8`)]);const metrics=overview.metrics||overview;const metricRows=Object.entries(metrics).filter(([,value])=>typeof value==='number').slice(0,6).map(([key,value])=>`<div class="metric"><strong>${fmt(value)}</strong><span>${esc(key.replaceAll('_',' '))}</span></div>`).join('');const timelineRows=(timeline||[]).slice(-8).reverse().map(row=>`<div class="row"><strong>${esc(row.year)}</strong><small>${fmt(row.citing_cases||0)} citing decisions · ${fmt(row.occurrences||0)} mentions</small></div>`).join('')||'<div class="empty">No timeline data.</div>';const outcomeRows=Object.entries(outcomes||{}).filter(([,value])=>typeof value==='number').map(([key,value])=>`<div class="row"><strong>${esc(key.replaceAll('_',' '))}</strong><small>${fmt(value)} decisions</small></div>`).join('')||'<div class="empty">No outcome data.</div>';const listRows=(rows,labelKeys)=>rows.map(row=>{const label=labelKeys.map(key=>row[key]).find(Boolean)||'Not recorded';const count=row.count||row.citations||row.decisions||row.occurrences||0;return `<div class="row"><strong>${esc(label)}</strong><small>${fmt(count)} records</small></div>`}).join('')||'<div class="empty">No data.</div>';const statuteRows=listRows(statutes,['label','value','statute']);box.innerHTML=`<section class="panel-section"><h4>Citation intelligence</h4><p class="section-note">Live signals calculated from this case's stored citation network.</p><div class="metric-grid">${metricRows||'<div class="empty">No overview metrics.</div>'}</div><div style="padding:0 14px 12px"><a class="row-link" href="/citation-intelligence?case_id=${caseId}">Open full Intel workspace ↗</a></div></section><section class="panel-section"><h4>Use over time</h4>${timelineRows}</section><section class="panel-section"><h4>Outcomes in citing decisions</h4>${outcomeRows}</section><section class="panel-section"><h4>Courts citing this case</h4>${listRows(courts,['court','label'])}</section><section class="panel-section"><h4>Judges citing this case</h4>${listRows(judges,['judge','name','label'])}</section><section class="panel-section"><h4>Statutes cited alongside this case</h4>${statuteRows}</section>`}catch(error){box.innerHTML=`<div class="empty">Unable to load citation intelligence: ${esc(error.message)}</div>`}}
		function renderCard(data){const c=data.case;const stats=citationSummary(data);document.getElementById('card').innerHTML=`<span class="citation">${esc(c.citation||'No neutral citation')}</span><h3>${esc(c.title)}</h3><p class="card-summary">${esc(c.court)} · ${esc(c.date)}${c.jurisdiction?`<br>${esc(c.jurisdiction)}`:''}${c.summary?`<br>${esc(String(c.summary).slice(0,180))}${String(c.summary).length>180?'…':''}`:''}</p><div class="card-stats"><span class="stat"><strong>${fmt(stats.total)}</strong><span>citation rows</span></span><span class="stat"><strong>${fmt(data.chunks?.length||0)}</strong><span>chunks</span></span><span class="stat"><strong>${fmt(stats.unresolved)}</strong><span>unresolved</span></span></div><div class="quick"><a href="/citation-map?case_id=${c.id}">Map view</a><a href="/citation-intelligence?case_id=${c.id}">Citation intel</a>${c.source_url?`<a href="${esc(c.source_url)}" target="_blank" rel="noreferrer">Original source</a>`:'<a href="javascript:void(0)">No source URL</a>'}</div>`}
		async function openCase(id){state.selected=id;state.data=null;document.getElementById('reader').innerHTML='<div class="empty">Loading case details...</div>';const data=await json(`/cases/${id}/reader-data`);state.data=data;const intelNav=document.getElementById("citationIntelNav");if(intelNav)intelNav.href=`/citation-intelligence?case_id=${id}`;renderDocument(data);renderCard(data);renderPanel();history.replaceState(null,'',`/case-reader?case_id=${id}`);document.getElementById('reader').scrollTop=0;document.querySelectorAll('.result').forEach(button=>button.classList.toggle('active',+button.dataset.id===id))}
		document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{state.tab=t.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===t));if(state.tab==='intel'){loadIntel()}else if(state.tab==='activity'){loadActivity()}else if(state.tab==='tags'){renderTags()}else if(state.tab==='acts'){renderActsRegs()}else{renderPanel();if(state.tab==='qa'){renderInfoDetails()}}});
		lucide.createIcons();
		const params=new URLSearchParams(location.search);const initial=params.get('case_id');
		loadReviewList().catch(error=>document.getElementById('results').innerHTML=`<div class="empty">${esc(error.message)}</div>`)
		if(initial)openCase(+initial).catch(error=>document.getElementById('reader').innerHTML=`<div class="empty">${esc(error.message)}</div>`);
		function renderInfoDetails(){const panel=document.getElementById('panel'),data=state.data||{},caseData=data.case||{},sourceLink=caseData.source_url?`<a href="${esc(caseData.source_url)}" target="_blank" rel="noreferrer">Open original source</a>`:'No source URL recorded';panel.insertAdjacentHTML('afterbegin',`<section class="panel-section"><h4>Record context</h4><div class="row"><div class="field"><b>status</b><span>${esc(caseData.processing_status||'Not recorded')}</span></div></div><div class="row"><div class="field"><b>source</b><span>${esc(caseData.source_name||caseData.source_type||'Not recorded')}</span></div>${sourceLink}</div><div class="row"><div class="field"><b>jurisdiction</b><span>${esc(caseData.jurisdiction||'Not recorded')}</span></div></div><div class="row"><div class="field"><b>tags</b><span>${fmt((data.tags||[]).length)}</span></div></div></section>`)}
		function renderTags(){const box=document.getElementById('panel'),tags=(state.data?.tags||[]).filter(tag=>tag.source==='reader_keyword');if(!tags.length){box.innerHTML='<div class="empty">No live tag candidates were generated from this decision.</div>';return}box.innerHTML=`<section class="panel-section"><h4>Live tag candidates</h4><p class="section-note">Generated from this decision at read time. These candidates are not written to the inventory.</p>${tags.map(tag=>`<div class="row"><strong>${esc(tag.category||'other')}: ${esc(tag.value)}</strong><small>${esc(tag.evidence||'No evidence excerpt')} · ${Math.round(Number(tag.score||0)*100)}% · live generated</small></div>`).join('')}</section>`}
		function renderActsRegs(){const box=document.getElementById('panel'),rows=(state.data?.citations||[]).filter(row=>row.provenance==='statute_references');if(!rows.length){box.innerHTML='<div class="empty">No persisted IRPA or IRPR statute references were found in this decision.</div>';return}const groups=new Map();rows.forEach(row=>{const label=String(row.normalized_citation||row.citation_text||'IRPA / IRPR reference').trim();const key=label.toLocaleLowerCase();const group=groups.get(key)||{label,rows:[]};group.rows.push(row);groups.set(key,group)});box.innerHTML=`<section class="panel-section"><h4 style="color:#6b3f91">Acts / Regulations</h4><p class="section-note">Persisted statute-reference table rows only. Live statute extraction is excluded here.</p>${[...groups.values()].sort((a,b)=>b.rows.length-a.rows.length||a.label.localeCompare(b.label)).map(group=>`<details style="margin:0 14px 8px;border:1px solid #d9c8e8;background:#faf7fd;color:#4f2d70"><summary style="padding:8px;cursor:pointer"><strong>${esc(group.label)}</strong><span style="float:right">${fmt(group.rows.length)} occurrence${group.rows.length===1?'':'s'}</span></summary>${group.rows.map(row=>`<div class="row"><strong>${esc(row.citation_text||group.label)}</strong><small>chunk ${row.chunk_id??'-'} · ${row.offset_start??'-'}-${row.offset_end??'-'} · statute table</small></div>`).join('')}</details>`).join('')}</section>`}
		async function loadActivity(){const box=document.getElementById('panel'),caseId=state.selected;if(!caseId){box.innerHTML='<div class="empty">Select a case to inspect FC activity.</div>';return}box.innerHTML='<div class="empty">Loading FC activity...</div>';try{const data=await json(`/cases/${caseId}/activity`),formatDate=value=>value?toDate(value):'Date unavailable',entryRows=[];(data.procedural_history||[]).forEach(history=>(history.entries||[]).forEach(entry=>entryRows.push(`<div class="row"><strong>${esc(entry.date||'Activity entry')}</strong><small>${esc(entry.entry||'No activity text')}</small><div class="badge">Procedural history · ${esc(history.imm_number)}</div></div>`)));(data.activity_cases||[]).forEach(activity=>(activity.documents||[]).forEach(document=>entryRows.push(`<div class="row"><strong>${esc(formatDate(document.doc_dt)||'Activity entry')}</strong><small>${esc(document.recorded_entry||'No recorded entry')}</small><div class="badge">${esc(activity.citation||'FC activity')} · ${esc(document.docno||document.re_no||'document')}</div></div>`)));const activityCaseRows=(data.activity_cases||[]).map(activity=>`<div class="row"><strong>${esc(activity.case_name||activity.citation||'Federal Court case')}</strong><small>${esc(activity.citation||'No IMM number')} · filed ${esc(formatDate(activity.date_filed))}${activity.city_filed?` · ${esc(activity.city_filed)}`:''}</small>${activity.source_url?`<a href="${esc(activity.source_url)}" target="_blank" rel="noreferrer">Open FC activity source</a>`:''}</div>`).join('');if(!data.imm_numbers?.length){box.innerHTML='<div class="empty">No IMM link is recorded for this case, so no FC activity is shown.</div>';return}if(!entryRows.length&&!activityCaseRows){box.innerHTML=`<div class="empty">Linked IMM ${esc(data.imm_numbers.join(', '))} has no stored FC activity entries yet.</div>`;return}box.innerHTML=`<section class="panel-section"><h4>Linked Federal Court activity</h4><p class="section-note">Exact IMM link: ${esc(data.imm_numbers.join(', '))}</p>${activityCaseRows}</section><section class="panel-section"><h4>Activity entries</h4>${entryRows.join('')||'<div class="empty">No detailed entries stored.</div>'}</section>`}catch(error){box.innerHTML=`<div class="empty">Unable to load FC activity: ${esc(error.message)}</div>`}}
	</script>
</body></html>"""
