"""Curated immigration-law synonym list used to widen plain-language searches.

Each entry maps a word people type to words and short phrases that decisions use for the same idea.
It is plain data, reviewed by hand, and applied only to the query (never to stored text); no model is
involved. A search word and its synonyms are alternatives for one slot, so "doctor" can be satisfied by
"physician" or "psychologist". Multi-word synonyms are matched as exact phrases.
"""

from __future__ import annotations

THESAURUS: dict[str, tuple[str, ...]] = {
	# Evidence and credibility
	"medical": ("psychological", "psychiatric", "physician", "doctor", "diagnosis", "clinical", "hospital"),
	"doctor": ("physician", "psychologist", "psychiatrist", "medical practitioner", "clinician"),
	"psychologist": ("psychotherapist", "psychological report", "counsellor"),
	"trauma": ("post-traumatic", "ptsd", "psychological harm", "traumatic"),
	"ignored": ("failed to consider", "did not consider", "overlooked", "disregarded", "failed to address", "ignored"),
	"ignore": ("fail to consider", "overlook", "disregard"),
	"evidence": ("documents", "documentary", "testimony", "proof", "material"),
	"documents": ("documentary evidence", "records", "paperwork"),
	"fake": ("fraudulent", "forged", "counterfeit", "false", "fabricated"),
	"forged": ("fraudulent", "counterfeit", "fabricated"),
	"liar": ("not credible", "lack of credibility", "untruthful"),
	"believe": ("credible", "credibility", "trust", "accept"),
	"disbelieve": ("not credible", "adverse credibility", "lack of credibility"),
	"inconsistent": ("inconsistencies", "contradictions", "discrepancies", "contradictory"),
	"inconsistencies": ("contradictions", "discrepancies", "omissions"),
	"story": ("narrative", "allegations", "account", "testimony"),
	"unreasonable": ("irrational", "arbitrary", "patently unreasonable"),
	"unfair": ("procedural fairness", "natural justice", "denied a fair hearing", "breach of fairness"),
	"biased": ("bias", "reasonable apprehension of bias", "partial"),
	"reasons": ("reasoning", "justification", "explanation", "adequacy of reasons"),
	"lawyer": ("counsel", "representative", "consultant", "legal representative"),
	"consultant": ("representative", "immigration consultant", "ghost consultant"),
	"interpreter": ("translation", "translator", "interpretation"),
	"translation": ("interpreter", "translator", "interpretation error"),
	# Decision makers and bodies
	"officer": ("visa officer", "immigration officer", "decision maker", "delegate", "agent"),
	"judge": ("justice", "court"),
	"board": ("tribunal", "panel", "member", "division"),
	"tribunal": ("board", "panel", "division"),
	"minister": ("government", "respondent", "mci", "mpsep"),
	"cbsa": ("border services", "border services agency", "canada border services agency"),
	"border": ("cbsa", "port of entry"),
	"appeal": ("appeal division", "appellant", "reconsideration"),
	"review": ("judicial review", "reviewing", "reviewable"),
	"stay": ("stay of removal", "stay of deportation", "injunction"),
	"leave": ("leave for judicial review", "permission"),
	# Refugee protection
	"asylum": ("refugee", "protection", "convention refugee", "refugee claim"),
	"refugee": ("asylum", "convention refugee", "protected person", "persecution"),
	"afraid": ("fear", "well-founded fear", "risk", "apprehension"),
	"fear": ("afraid", "well-founded fear", "risk", "subjective fear"),
	"persecuted": ("persecution", "serious harm", "discrimination", "mistreatment"),
	"persecution": ("serious harm", "ill-treatment", "mistreatment", "discrimination amounting to persecution"),
	"killed": ("murder", "death", "shot", "executed", "life threatening"),
	"kill": ("murder", "death threat", "assassinate", "harm"),
	"threatened": ("death threats", "threats", "intimidated", "harassed"),
	"threat": ("danger", "risk", "intimidation"),
	"torture": ("cruel and unusual", "inhuman treatment", "degrading treatment", "ill-treatment"),
	"police": ("law enforcement", "authorities", "security forces", "officers", "state agents"),
	"corruption": ("corrupt", "bribery", "bribes", "impunity", "collusion"),
	"corrupt": ("corruption", "bribery", "bribes"),
	"protection": ("state protection", "adequate protection", "safeguard", "recourse"),
	"government": ("state", "authorities", "regime"),
	"relocate": ("internal flight alternative", "ifa", "move within the country", "relocation"),
	"relocation": ("internal flight alternative", "ifa", "internal relocation"),
	"safe": ("viable", "reasonable", "secure", "safe country"),
	"flight": ("internal flight alternative", "ifa"),
	"gang": ("cartel", "criminal organization", "mafia", "criminal group", "organized crime"),
	"extortion": ("extort", "protection money", "blackmail", "shakedown"),
	"cartel": ("gang", "criminal organization", "narco"),
	"abusive": ("abuse", "violent", "domestic violence", "battered", "beating"),
	"abuse": ("domestic violence", "violence", "mistreatment", "assault", "battery"),
	"husband": ("spouse", "partner", "common-law partner", "ex-husband"),
	"wife": ("spouse", "partner", "common-law partner"),
	"woman": ("female", "women", "gender"),
	"women": ("female", "gender", "woman"),
	"gender": ("woman", "female", "gender-based violence", "sex"),
	"escaping": ("fleeing", "flee", "escape", "left"),
	"escape": ("flee", "fled", "left"),
	"flee": ("escape", "fled", "left the country"),
	"gay": ("homosexual", "lgbt", "lgbtq", "sexual orientation", "lesbian", "bisexual"),
	"lesbian": ("homosexual", "sexual orientation", "lgbt"),
	"transgender": ("trans", "gender identity", "lgbt"),
	"lgbt": ("sexual orientation", "gender identity", "homosexual"),
	"convert": ("conversion", "converted", "baptized", "apostasy"),
	"conversion": ("convert", "apostasy", "baptism", "religious conversion"),
	"christian": ("church", "pastor", "evangelical", "religion"),
	"muslim": ("islam", "islamic", "mosque"),
	"religion": ("religious", "faith", "belief", "church", "mosque"),
	"political": ("political opinion", "opposition", "activist", "party member"),
	"activist": ("political activity", "protester", "organizer", "advocate"),
	"opposition": ("opposition party", "political opposition", "dissident"),
	"arrested": ("detained", "detention", "apprehended", "taken into custody", "imprisoned"),
	"detained": ("detention", "arrested", "imprisoned", "custody"),
	"prison": ("jail", "imprisonment", "incarceration", "detention"),
	"fgm": ("female genital mutilation", "genital cutting", "female circumcision"),
	"genital": ("fgm", "mutilation", "circumcision", "cutting"),
	"daughter": ("girl", "child", "female child", "minor"),
	"mutilation": ("fgm", "genital cutting", "female circumcision"),
	"minor": ("child", "children", "underage", "youth"),
	"children": ("child", "minor", "minors", "kids", "best interests of the child"),
	"child": ("children", "minor", "best interests of the child", "dependent"),
	"orphan": ("unaccompanied minor", "no parents", "parentless"),
	"late": ("delay", "delayed", "waited", "untimely", "failure to claim"),
	"delay": ("late", "delayed", "waited", "untimely", "undue delay"),
	"withdrawn": ("abandoned", "abandonment", "withdrew", "no longer pursued"),
	"abandoned": ("withdrawn", "abandonment", "failed to appear", "failed to attend"),
	"showed": ("appear", "attend", "appeared"),
	"exclusion": ("article 1f", "excluded", "serious non-political crime", "complicity"),
	"crime": ("criminality", "offence", "criminal", "conviction"),
	"criminal": ("criminality", "conviction", "offence", "serious criminality"),
	"war": ("armed conflict", "civil war", "war crimes", "crimes against humanity"),
	"terrorism": ("terrorist", "security", "inadmissibility security"),
	"spy": ("espionage", "intelligence", "security"),
	"member": ("membership", "belong", "part of", "associated"),
	"social": ("particular social group", "psg", "membership"),
	"group": ("particular social group", "psg"),
	"npsg": ("particular social group",),
	# Procedure, admissibility and removal
	"deport": ("removal", "removed", "removal order", "deportation order"),
	"deportation": ("removal", "removal order", "deportation order", "removed from canada"),
	"removal": ("deportation", "removal order", "removed"),
	"inadmissible": ("inadmissibility", "not admissible", "excluded"),
	"inadmissibility": ("inadmissible", "not admissible"),
	"misrepresentation": ("misrepresent", "false statement", "fraud", "false information", "section 40"),
	"lied": ("misrepresentation", "false statement", "untruthful", "misrepresented"),
	"lie": ("misrepresentation", "false statement", "untruthful"),
	"fraud": ("misrepresentation", "fraudulent", "false", "deceit"),
	"visa": ("temporary resident visa", "trv", "permit", "authorization"),
	"permit": ("work permit", "study permit", "visa", "authorization"),
	"student": ("study permit", "international student", "studies", "dli"),
	"study": ("study permit", "student", "studies"),
	"work": ("work permit", "employment", "lmia", "employer"),
	"worker": ("work permit", "temporary foreign worker", "caregiver", "employee"),
	"employer": ("lmia", "labour market impact assessment", "job offer", "employment"),
	"caregiver": ("live-in caregiver", "nanny", "home care", "home support"),
	"spouse": ("husband", "wife", "partner", "common-law partner", "conjugal partner"),
	"marriage": ("marriage of convenience", "genuine marriage", "bad faith", "relationship"),
	"sponsor": ("sponsorship", "sponsored", "sponsoring", "undertaking"),
	"sponsorship": ("sponsor", "undertaking", "family class", "spousal sponsorship"),
	"family": ("family class", "relatives", "dependants"),
	"parent": ("parents", "parent and grandparent", "pgp", "father", "mother"),
	"citizenship": ("citizen", "naturalization", "residence requirement", "citizenship act"),
	"citizen": ("citizenship", "canadian citizen", "naturalization"),
	"residency": ("residence obligation", "permanent resident", "residency obligation", "physical presence"),
	"pr": ("permanent resident", "permanent residence", "landed immigrant"),
	"express": ("express entry", "crs", "comprehensive ranking system", "ita"),
	"points": ("score", "crs", "ranking", "selection criteria"),
	"humanitarian": ("h&c", "humanitarian and compassionate", "hardship", "section 25", "compassionate"),
	"hardship": ("unusual and undeserved", "disproportionate hardship", "humanitarian", "h&c"),
	"establishment": ("degree of establishment", "settled", "integration", "ties to canada"),
	"pre-removal": ("prra", "risk assessment", "pre-removal risk assessment"),
	"prra": ("pre-removal risk assessment", "risk assessment", "pre-removal"),
	"detention": ("detained", "custody", "flight risk", "detention review", "immigration division"),
	"bond": ("release", "deposit", "bail", "guarantee", "conditions of release"),
	"bail": ("bond", "release", "conditions of release"),
	"delay-in-processing": ("mandamus", "processing times", "unreasonable delay"),
	"mandamus": ("compel", "writ", "unreasonable delay", "processing delay"),
	"waiting": ("delay", "processing time", "backlog", "mandamus"),
	"standard": ("standard of review", "reasonableness", "correctness", "vavilov"),
	"reasonableness": ("unreasonable", "reasonable", "vavilov", "justification transparency intelligibility"),
	"fairness": ("procedural fairness", "natural justice", "duty of fairness", "fair hearing"),
	"costs": ("special reasons", "costs award", "rule 22"),
	"certified": ("certified question", "serious question of general importance", "question of general importance"),
	"covid": ("pandemic", "covid-19", "coronavirus", "lockdown"),
	"consent": ("consent judgment", "settlement", "discontinued", "agreed"),
	"judgment": ("decision", "order", "ruling", "reasons for judgment"),
	"overturned": ("set aside", "quashed", "allowed", "remitted", "sent back"),
	"quashed": ("set aside", "overturned", "allowed", "remitted"),
	"won": ("allowed", "granted", "successful", "set aside"),
	"lost": ("dismissed", "refused", "rejected", "unsuccessful"),
	"rejected": ("refused", "denied", "dismissed", "negative decision"),
	"refused": ("rejected", "denied", "dismissed", "negative decision"),
	"denied": ("refused", "rejected", "dismissed"),
}


def synonyms_for(word: str) -> tuple[str, ...]:
	"""Synonyms for a lower-cased query word (also tries the singular form)."""
	word = word.lower()
	if word in THESAURUS:
		return THESAURUS[word]
	if word.endswith("s") and word[:-1] in THESAURUS:
		return THESAURUS[word[:-1]]
	return ()
