from __future__ import annotations


def case_reader_html() -> str:
	return r"""<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
	<title>Case Reader | AI CaseLibrary</title>
	<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&family=Newsreader:opsz,wght@6..72,600;6..72,700&display=swap" rel="stylesheet">
	<script src="https://unpkg.com/lucide@0.468.0/dist/umd/lucide.min.js"></script>
	<style>
		:root{--ink:#202522;--muted:#69726d;--paper:#f1efe8;--surface:#fffef9;--line:#d8d5ca;--rust:#a4412b;--teal:#176c68;--blue:#315d8d}*{box-sizing:border-box}body{margin:0;min-height:100vh;color:var(--ink);font-family:"IBM Plex Sans",sans-serif;letter-spacing:0;background:var(--paper);background-image:linear-gradient(rgba(32,37,34,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(32,37,34,.035) 1px,transparent 1px);background-size:26px 26px}button,input{font:inherit;letter-spacing:0}button{cursor:pointer}
		.top{height:68px;display:flex;align-items:center;justify-content:space-between;padding:0 24px;border-bottom:1px solid var(--line);background:rgba(255,254,249,.97)}.brand{display:flex;align-items:baseline;gap:13px}.brand h1{margin:0;font:700 28px/1 "Newsreader",serif}.brand span{color:var(--muted);font-size:12px}.nav{display:flex;gap:5px}.nav a{display:flex;align-items:center;gap:6px;padding:8px 10px;border-radius:5px;color:var(--muted);font-size:11px;text-decoration:none}.nav a.active{background:var(--ink);color:white}.nav i{width:15px;height:15px}
		.shell{display:grid;grid-template-columns:330px minmax(0,1fr);height:calc(100vh - 68px)}.index{min-width:0;border-right:1px solid var(--line);background:rgba(255,254,249,.93)}.head{padding:18px;border-bottom:1px solid var(--line)}h2{margin:0;font:600 21px/1.15 "Newsreader",serif}.search{position:relative;margin-top:12px}.search i{position:absolute;left:11px;top:11px;width:16px;color:var(--muted)}.search input{width:100%;height:39px;padding:8px 10px 8px 36px;border:1px solid var(--line);border-radius:5px;background:var(--surface);outline:0}.search input:focus{border-color:var(--teal)}.hint{margin:9px 0 0;color:var(--muted);font-size:10px}.results{height:calc(100% - 126px);overflow:auto}.result{width:100%;padding:13px 17px;border:0;border-bottom:1px solid #e9e6dd;background:transparent;text-align:left;color:var(--ink)}.result:hover,.result.active{background:#edf3f0}.result strong{display:block;font-size:12px;line-height:1.35}.result small{display:block;margin-top:4px;color:var(--muted);font-size:10px}.empty{padding:24px 18px;color:var(--muted);font-size:11px;line-height:1.55}
		.reader{min-width:0;overflow:auto;background:rgba(255,254,249,.74)}.document{max-width:900px;margin:0 auto;padding:48px clamp(28px,7vw,90px) 90px}.eyebrow{color:var(--rust);font-size:11px;font-weight:600;text-transform:uppercase}.document h2{margin:10px 0 12px;font-size:clamp(27px,4vw,45px);line-height:1.04}.meta{display:flex;flex-wrap:wrap;gap:7px;margin-bottom:30px}.meta span,.meta a{padding:5px 7px;border:1px solid var(--line);border-radius:4px;color:var(--muted);font-size:10px;text-decoration:none}.meta a{color:var(--blue)}.text{padding-top:28px;border-top:1px solid var(--line);white-space:pre-wrap;font:16px/1.72 "Newsreader",serif}.placeholder{display:grid;min-height:100%;place-items:center;text-align:center}.placeholder div{max-width:390px}.placeholder i{width:34px;height:34px;color:var(--teal)}.placeholder h2{margin:14px 0 8px;font-size:28px}.placeholder p{margin:0;color:var(--muted);font-size:12px;line-height:1.6}
		@media(max-width:760px){.top{height:auto;min-height:64px;padding:10px 14px}.brand span{display:none}.shell{grid-template-columns:1fr;height:auto}.index{height:300px;border-right:0;border-bottom:1px solid var(--line)}.results{height:174px}.reader{min-height:calc(100vh - 364px)}.document{padding:32px 20px 60px}.text{font-size:15px}.nav a{padding:8px}.nav a span{display:none}}
	</style>
</head>
<body>
	<header class="top"><div class="brand"><h1>Case Reader</h1><span>Search and read the corpus</span></div><nav class="nav"><a href="/citation-map"><i data-lucide="network"></i><span>Citation Map</span></a><a class="active" href="/case-reader"><i data-lucide="book-open"></i><span>Case Reader</span></a></nav></header>
	<main class="shell"><aside class="index"><div class="head"><h2>Find a decision</h2><div class="search"><i data-lucide="search"></i><input id="search" type="search" autocomplete="off" placeholder="Case name or citation"></div><p class="hint">Search by party name, case name, or neutral citation.</p></div><div id="results" class="results"><div class="empty">Start typing to search 35,902 decisions.</div></div></aside><section id="reader" class="reader"><div class="placeholder"><div><i data-lucide="book-open"></i><h2>Select a case to read</h2><p>The canonical stored decision text will appear here with its source and citation.</p></div></div></section></main>
	<script>
		const state={timer:null,selected:null};const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
		async function json(url){const response=await fetch(url);if(!response.ok)throw new Error(`Request failed: ${response.status}`);return response.json()}
		function renderResults(rows){const box=document.getElementById('results');box.innerHTML=rows.map(item=>`<button class="result ${item.case_id===state.selected?'active':''}" data-id="${item.case_id}"><strong>${esc(item.title)}</strong><small>${esc(item.citation||'No neutral citation')} · ${esc(item.court)} · ${esc(item.date)}</small></button>`).join('')||'<div class="empty">No matching cases.</div>';box.querySelectorAll('button').forEach(button=>button.onclick=()=>openCase(+button.dataset.id))}
		async function search(){const query=document.getElementById('search').value.trim();if(query.length<2){document.getElementById('results').innerHTML='<div class="empty">Enter at least two characters.</div>';return}renderResults(await json(`/citation-map/cases?q=${encodeURIComponent(query)}&limit=30`))}
		async function openCase(id){state.selected=id;document.getElementById('reader').innerHTML='<div class="empty">Loading decision...</div>';const item=await json(`/cases/${id}`),text=item.full_text||item.summary||'No decision text is stored for this case.';document.title=`${item.title} | Case Reader`;document.getElementById('reader').innerHTML=`<article class="document"><div class="eyebrow">${esc(item.citation||'No neutral citation')}</div><h2>${esc(item.title)}</h2><div class="meta"><span>${esc(item.court)}</span><span>${esc(item.date)}</span>${item.source_name?`<span>${esc(item.source_name)}</span>`:''}${item.source_url?`<a href="${esc(item.source_url)}" target="_blank" rel="noreferrer">Original source</a>`:''}<a href="/citation-map?case_id=${id}">Open citation map</a></div><div class="text">${esc(text)}</div></article>`;history.replaceState(null,'',`/case-reader?case_id=${id}`);document.getElementById('reader').scrollTop=0;document.querySelectorAll('.result').forEach(button=>button.classList.toggle('active',+button.dataset.id===id))}
		document.getElementById('search').oninput=()=>{clearTimeout(state.timer);state.timer=setTimeout(()=>search().catch(error=>document.getElementById('results').innerHTML=`<div class="empty">${esc(error.message)}</div>`),220)};lucide.createIcons();const initial=new URLSearchParams(location.search).get('case_id');if(initial)openCase(+initial).catch(()=>{});
	</script>
</body></html>"""