param(
    [Parameter(Mandatory = $true)]
    [string]$Hostname,
    [string]$TunnelName = "aicaselibrary-local",
    [string]$LocalHost = "127.0.0.1",
    [int]$LocalPort = 8070,
    [string]$ConfigPath = ".cloudflared/config.yml"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-RepoRoot {
    return (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

function Ensure-Cloudflared {
    $cmd = Get-Command cloudflared -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }

    $knownPath = "C:\Program Files (x86)\cloudflared\cloudflared.exe"
    if (Test-Path $knownPath) {
        $env:Path = "C:\Program Files (x86)\cloudflared;" + $env:Path
        return $knownPath
    }

    Write-Host "cloudflared not found in PATH. Attempting installation via winget..."
    winget install --id Cloudflare.cloudflared --exact --accept-package-agreements --accept-source-agreements

    $cmd = Get-Command cloudflared -ErrorAction SilentlyContinue
    if (-not $cmd) {
        throw "cloudflared is still not available. Install manually from https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
    }

    return $cmd.Source
}

function Get-TunnelByName([string]$Name) {
    $raw = cloudflared tunnel list --output json
    if (-not $raw) {
        return $null
    }

    if ($raw.Trim() -eq "null") {
        return $null
    }

    $rows = $raw | ConvertFrom-Json
    if ($null -eq $rows) {
        return $null
    }

    if ($rows.PSObject.Properties.Name -contains "result") {
        $rows = $rows.result
    }

    if ($rows -isnot [System.Array]) {
        $rows = @($rows)
    }

    return $rows | Where-Object { $_.name -eq $Name } | Select-Object -First 1
}

$repoRoot = Get-RepoRoot
Push-Location $repoRoot
try {
    $cloudflaredPath = Ensure-Cloudflared
    Write-Host "Using cloudflared at: $cloudflaredPath"

    $originCert = Join-Path $env:USERPROFILE ".cloudflared/cert.pem"
    if (-not (Test-Path $originCert)) {
        Write-Host "Running browser login for Cloudflare account authorization..."
        cloudflared tunnel login
    }

    $existing = Get-TunnelByName -Name $TunnelName
    if (-not $existing) {
        Write-Host "Creating tunnel '$TunnelName'..."
        cloudflared tunnel create $TunnelName | Out-Host
        $existing = Get-TunnelByName -Name $TunnelName
    }

    if (-not $existing) {
        throw "Unable to find tunnel '$TunnelName' after creation."
    }

    $tunnelId = $existing.id
    $credentialsFile = Join-Path $env:USERPROFILE ".cloudflared/$tunnelId.json"
    if (-not (Test-Path $credentialsFile)) {
        throw "Tunnel credentials file not found at $credentialsFile"
    }

    Write-Host "Routing DNS for $Hostname -> tunnel '$TunnelName'..."
    cloudflared tunnel route dns $TunnelName $Hostname | Out-Host

    $configDir = Split-Path -Parent (Join-Path $repoRoot $ConfigPath)
    if (-not (Test-Path $configDir)) {
        New-Item -Path $configDir -ItemType Directory -Force | Out-Null
    }

    $resolvedConfigPath = (Join-Path $repoRoot $ConfigPath)
    $yaml = @"
# Auto-generated by scripts/setup_cloudflare_tunnel.ps1
tunnel: $tunnelId
credentials-file: $credentialsFile

ingress:
  - hostname: $Hostname
    service: http://${LocalHost}:${LocalPort}
  - service: http_status:404
"@

    Set-Content -Path $resolvedConfigPath -Value $yaml -Encoding UTF8

    Write-Host ""
    Write-Host "Cloudflare Tunnel setup complete."
    Write-Host "Config written to: $resolvedConfigPath"
    Write-Host ""
    Write-Host "Next steps:"
    Write-Host "1) Start API: .\\venv\\Scripts\\python.exe -m uvicorn backend.main:app --host $LocalHost --port $LocalPort"
    Write-Host "2) Start tunnel: cloudflared tunnel --config $resolvedConfigPath run"
    Write-Host "3) Open https://$Hostname"
}
finally {
    Pop-Location
}
